# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix focus issues when dialogs are opened or closed
# windowrulev2 = windowdance,class:^(jetbrains-.*)$,floating:1
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule = center on, no_focus on, border_size 0, match:class ^(jetbrains-.*)$, match:title ^(splash)$, match:float 1

windowrule = no_initial_focus on, match:class ^jetbrains-.*$, match:float 1, match:title ^$|^\s$|^win\d+$
# -- End of IntelliJ Rules --
