;;; i3wm-config-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from i3wm-config-mode.el

(autoload 'i3wm-config-mode "i3wm-config-mode" "\


(fn)" t)
(add-to-list 'auto-mode-alist '("i3/config\\'" . i3wm-config-mode))
(register-definition-prefixes "i3wm-config-mode" '("i3wm-config-font-lock-keywords"))

;;; End of scraped data

(provide 'i3wm-config-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; i3wm-config-mode-autoloads.el ends here
