palette = 0= {{base16.base00.dark.hex}}
palette = 1= {{base16.base08.dark.hex}}
palette = 2= {{base16.base0b.dark.hex}}
palette = 3= {{base16.base0a.dark.hex}}
palette = 4= {{base16.base0d.dark.hex}}
palette = 5= {{base16.base0e.dark.hex}}
palette = 6= {{base16.base0c.dark.hex}}
palette = 7= {{base16.base07.dark.hex}}
palette = 8= {{base16.base08.dark.hex}}
palette = 9=  {{base16.base08.dark.hex}}
palette = 10= {{base16.base0b.default.hex}}
palette = 11= {{base16.base0a.dark.hex}}
palette = 12= {{base16.base0d.dark.hex}}
palette = 13= {{base16.base0e.dark.hex}}
palette = 14= {{base16.base0c.dark.hex}}
palette = 15= {{colors.on_surface.default.hex}}
background = {{colors.surface.default.hex}}
foreground = {{colors.on_surface.default.hex}}
cursor-color = {{colors.on_surface.default.hex}}
cursor-text = {{colors.surface.default.hex}}
selection-background = {{colors.tertiary.default.hex}}
selection-foreground = {{colors.on_tertiary.default.hex}}
