# Fondo y texto principal
background {{colors.surface.default.hex}}
foreground {{colors.on_surface.default.hex}}

# Cursor (Usamos el acento principal para que destaque, y su color de texto opuesto para que se lea lo que hay debajo)
cursor {{colors.primary.default.hex}}
cursor_text_color {{colors.on_primary.default.hex}}

# Selección (Fondo sutil con texto legible)
selection_background {{colors.surface_variant.default.hex}}
selection_foreground {{colors.on_surface.default.hex}}

# Negros (Sustituimos el negro puro por fondos con contraste)
color0 {{colors.surface_container_highest.default.hex}}
color8 {{colors.surface_variant.default.hex}}

# Rojos (Errores)
color1 {{colors.error.default.hex}}
color9 {{colors.error.default.hex}}

# Verdes (Como MD3 no tiene "verde", usamos el token terciario)
color2 {{colors.tertiary.default.hex}}
color10 {{colors.tertiary.default.hex}}

# Amarillos (Acentos secundarios)
color3 {{colors.secondary.default.hex}}
color11 {{colors.secondary.default.hex}}

# Azules (Acentos principales)
color4 {{colors.primary.default.hex}}
color12 {{colors.primary.default.hex}}

# Magentas / Morados
color5 {{colors.inverse_primary.default.hex}}
color13 {{colors.inverse_primary.default.hex}}

# Cianes (Usamos los contenedores para variar el tono)
color6 {{colors.primary_container.default.hex}}
color14 {{colors.secondary_container.default.hex}}

# Blancos / Textos (Garantiza máxima legibilidad)
color7 {{colors.on_surface_variant.default.hex}}
color15 {{colors.on_surface.default.hex}}