# ~/.config/hypr/configs/keybinds/apps.conf

##! Utilidades y herramientas del sistema
bind = $mainMod, Return, exec, uwsm app -- $terminal # Abrir terminal
bind = $mainMod, F, exec, uwsm app -- $fileManager # Abrir gestor de archivos
bind = ALT, Space, exec, uwsm app -- $menu # Abrir menú general
bind = $mainMod, Space, exec, uwsm app -- $menu -s hyprsphere # Abrir menú del sistema
bind = ALT, K, exec, uwsm app -- menubinds.sh # Abrir menú de atajos de teclado
bind = $mainMod, X, exec, dms ipc call settings focusOrToggle # Abrir menú del sistema (dms)

##! Aplicaciones de productividad y comunicación
bind = $mainMod, B, exec, uwsm app -- $browser # Abrir navegador
bind = $mainMod, E, exec, uwsm app -- $emacs # Ejecutar cliente Emacs
bind = SUPER, T, exec, uwsm app -- Telegram # Abrir cliente de Telegram
bind = $mainMod, D, exec, uwsm app -- vesktop # Abrir cliente Discord (Vesktop)
bind = $mainMod, Z, exec, uwsm app -- zapzap # Abrir cliente Whatsapp

##! Utilidades y herramientas adicionales
bind = ALT, V, exec, dms ipc clipboard toggle # Abrir menú del portapapeles
bind = ALT, E, exec, uwsm app -- $menu -m symbols # Abrir menú de emojis
bind = $mainMod, G, exec, uwsm app -- cartridges # Abrir Cartuchos
