bindd = $mainMod Shift, h, Mover ventana a la izquierda (Vim), movewindow, l
bindd = $mainMod Shift, l, Mover ventana a la derecha (Vim), movewindow, r
bindd = $mainMod Shift, k, Mover ventana hacia arriba (Vim), movewindow, u
bindd = $mainMod Shift, j, Mover ventana hacia abajo (Vim), movewindow, d

## Mover ventana activa con mainMod + Shift + flechas
bindd = $mainMod Shift, left, Mover ventana a la izquierda, movewindow, l
bindd = $mainMod Shift, right, Mover ventana a la derecha, movewindow, r
bindd = $mainMod Shift, up, Mover ventana hacia arriba, movewindow, u
bindd = $mainMod Shift, down, Mover ventana hacia abajo, movewindow, d

submap = resize
# resizeactive para hacerlo en modo normal, con scrolling usar colresize
$sr=($sm resize)
bindd = , escape, Salir del submap resize , submap, reset 
binded = , l, $sr Aumentar ventana izquierda (Vim), resizeactive, 10 0
binded = , h, $sr Aumentar ventana derecha (Vim), resizeactive, -10 0
binded = , k, $sr Aumentar ventana abajo (Vim), resizeactive, 0 -10 
binded = , j, $sr Aumentar ventana arriba (Vim), resizeactive, 0 10

binded = , right, $sr Aumentar ventana izquierda, resizeactive, 10 0
binded = , left, $sr Aumentar ventana derecha, resizeactive, -10 0
binded = , up, $sr Aumentar ventana abajo, resizeactive, 0 -10 
binded = , down, $sr Aumentar ventana arriba, resizeactive, 0 10

bind = , catchall, submap, reset
submap = reset
