# ~/.config/hypr/configs/keybinds/media.conf

# ╔═════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                   Controles multimedia y de sistema                             ║
# ╚═════════════════════════════════════════════════════════════════════════════════════════════════╝

# ---------------------------------------------------------------------------------------------------
# - Control de volumen y brillo
# ---------------------------------------------------------------------------------------------------
binded = , XF86AudioRaiseVolume, Subir volumen, exec, swayosd-client --output-volume=raise
binded = , XF86AudioLowerVolume, Bajar volumen, exec, swayosd-client --output-volume=lower
bindd = , XF86AudioMute, Silenciar audio, exec, swayosd-client --output-volume=mute-toggle
bindd = , XF86AudioMicMute, Silenciar micrófono, exec,swayosd-client --input-volume=mute-toggle
binded = , XF86MonBrightnessUp, Subir brillo, exec, swayosd-client --brightness=raise
binded = , XF86MonBrightnessDown, Bajar brillo, exec, swayosd-client --brightness=lower

# ---------------------------------------------------------------------------------------------------
# - Controles de reproducción (Submap)
# ---------------------------------------------------------------------------------------------------
$smm = ($sm Multimedia)
bindd = $mainMod, I, $smm Acceder al submapa multimedia, submap, Multimedia
submap = Multimedia
  bindd = , S, $smm Reproducir/Pausar, exec, swayosd-client --playerctl=play-pause
  bindd = , P, $smm Anterior, exec, swayosd-client --playerctl=previous
  bindd = , N, $smm Siguiente, exec, swayosd-client --playerctl=next
  bindd = , escape, $smm Salir del submapa, submap, reset
submap = reset

# ---------------------------------------------------------------------------------------------------
# - Capturas de pantalla
# ---------------------------------------------------------------------------------------------------
bindd = , Print, Capturar pantalla completa, exec, hyprshot -m output -m eDP-1
bindd = $mainMod, Print, Capturar selección, exec, hyprshot -m region --raw | satty --filename -
bindd = Ctrl, Print, Abrir menú de capturas, exec, walker -m menus:screenshot
