# ~/.config/hypr/configs/keybinds/media.conf

# ╔═════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                   Controles multimedia y de sistema                             ║
# ╚═════════════════════════════════════════════════════════════════════════════════════════════════╝

# ---------------------------------------------------------------------------------------------------
# - Control de volumen y brillo
# ---------------------------------------------------------------------------------------------------
binded = , XF86AudioRaiseVolume, Subir volumen, exec, dms ipc call audio increment 10
binded = , XF86AudioLowerVolume, Bajar volumen, exec, dms ipc call audio decrement 10
bindd = , XF86AudioMute, Silenciar audio, exec,  dms ipc call audio mute
bindd = , XF86AudioMicMute, Silenciar micrófono, exec,dms ipc call audio micmute
binded = , XF86MonBrightnessUp, Subir brillo, exec, dms ipc call brightness increment 10 ""
binded = , XF86MonBrightnessDown, Bajar brillo, exec,  dms ipc call brightness decrement 10 ""

# ---------------------------------------------------------------------------------------------------
# - Controles de reproducción (Submap)
# ---------------------------------------------------------------------------------------------------
$smm = ($sm Multimedia)
bindd = $mainMod, I, $smm Acceder al submapa multimedia, submap, Multimedia
submap = Multimedia
  bindd = , S, $smm Reproducir/Pausar, exec, swayosd-client --playerctl=play-pause
  bindd = , P, $smm Anterior, exec, swayosd-client --playerctl=previous
  bindd = , N, $smm Siguiente, exec, swayosd-client --playerctl=next
  bindd = , escape, $smm Salir del submapa, submap, reset
submap = reset

# ---------------------------------------------------------------------------------------------------
# - Capturas de pantalla
# ---------------------------------------------------------------------------------------------------
bindd = , Print, Capturar pantalla completa, exec, screenshoter
bindd = $mainMod, Print, Capturar selección, exec, screenshoter selection
bindd = Ctrl, Print, Abrir menú de capturas, exec, walker -m menus:screenshot
