# ~/.config/hypr/configs/keybinds/system.conf

# ╔═════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                     Atajos de sistema y varios                                    ║
# ╚═════════════════════════════════════════════════════════════════════════════════════════════════╝

# ---------------------------------------------------------------------------------------------------
# - Acciones del sistema y de la sesión
# ---------------------------------------------------------------------------------------------------
bindd = $mainMod Shift, E, Abrir menú de apagado, exec, wlogout -b 5
bindd = $mainMod, F1, Activar o desactivar modo de juego, exec, bash -c "toggle-gamemode.sh"
bindd = $mainMod, X, Abrir cambiador de menu, exec, $menu_layout_changer
bindd = $mainMod, L, Bloquear pantalla, exec, hyprlock
#bindd = Alt, C, Alternar modo "No molestar", exec, ags request dontDisturbToggle
bindd = Alt, C, Alternar modo "No molestar", exec, swaync-client --toggle-dnd
bindd = Alt, D, Toggleing dashboard, exec, ags request toggle dashboard
bindd = $mainMod, N, Abrir panel de notificaciones, exec, swaync-client --toggle-panel
#bindd = $mainMod, N, Abrir panel de notificaciones, exec, ags request toggle notifications

#bind = $mainMod SHIFT, N, exec, dms ipc call notepad toggle
# ---------------------------------------------------------------------------------------------------
# - Control de la barra de estado (Waybar)
# ---------------------------------------------------------------------------------------------------
##bindd = Alt, N, Cambiar diseño de Waybar, exec, uwsm app -- $menu -m menus:waybar-layout-selector
bindd = Alt, N, Cambiar diseño de Waybar, exec, uwsm app -- $bar_layout_selector
bindd = $mainMod, R, Reiniciar Waybar, exec, launch-waybar
#bindd = $mainMod, R, Reiniciar Waybar, exec, ags request restart

# ---------------------------------------------------------------------------------------------------
# - Tiling y fondos de pantalla
# ---------------------------------------------------------------------------------------------------
bindd = $mainMod, P, Activar/desactivar Pseudo Tiling, pseudo,
bindd = $mainMod Alt, J, Cambiar tipo de división (split), layoutmsg, togglesplit,
#bindd = $mainMod, W, Cambiar fondo de pantalla, exec, walker -m menus:wallpapers
bindd = $mainMod, W, Cambiar fondo de pantalla, exec, $wallpaper_selector

# ---------------------------------------------------------------------------------------------------
# - Movimiento y redimensionamiento con el ratón
# ---------------------------------------------------------------------------------------------------
bindmd = $mainMod, mouse:272, Mover ventana con el ratón, movewindow
bindmd = $mainMod, mouse:273, Redimensionar ventana con el ratón, resizewindow

# ---------------------------------------------------------------------------------------------------
# - Submapa Passthrough
# ---------------------------------------------------------------------------------------------------
$sp = ($sm Passthrough)
bindd = $mainMod, escape, Acceder al submapa Passthrough, submap, Passthrough

submap = Passthrough
  bindd = , escape, Salir del submapa, submap, reset
submap = reset
