# ~/.config/hypr/configs/keybinds/system.conf

# ╔═════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                     Atajos de sistema y varios                                    ║
# ╚═════════════════════════════════════════════════════════════════════════════════════════════════╝

# ---------------------------------------------------------------------------------------------------
# - Acciones del sistema y de la sesión
# ---------------------------------------------------------------------------------------------------
bindd = $mainMod Shift, E, Abrir menú de apagado, exec, uwsm app -- $menu -m menus:power-menu
bindd = $mainMod, F1, Activar o desactivar modo de juego, exec, bash -c "toggle-gamemode.sh"
bindd = Alt, C, Alternar modo "No molestar", exec, swaync-client -d
bindd = $mainMod, N, Abrir panel de notificaciones, exec, uwsm app -- swaync-client -t -sw

# ---------------------------------------------------------------------------------------------------
# - Control de la barra de estado (Waybar)
# ---------------------------------------------------------------------------------------------------
bindd = Alt, N, Cambiar diseño de Waybar, exec, uwsm app -- $menu -m menus:waybar-layout-selector
bindd = $mainMod, R, Reiniciar Waybar, exec, launch-waybar

# ---------------------------------------------------------------------------------------------------
# - Tiling y fondos de pantalla
# ---------------------------------------------------------------------------------------------------
bindd = $mainMod, P, Activar/desactivar Pseudo Tiling, pseudo,
bindd = $mainMod Alt, J, Cambiar tipo de división (split), togglesplit,
bindd = $mainMod, W, Cambiar fondo de pantalla, exec, $menu -m menus:wallpapers

# ---------------------------------------------------------------------------------------------------
# - Movimiento y redimensionamiento con el ratón
# ---------------------------------------------------------------------------------------------------
bindmd = $mainMod, mouse:272, Mover ventana con el ratón, movewindow
bindmd = $mainMod, mouse:273, Redimensionar ventana con el ratón, resizewindow

# ---------------------------------------------------------------------------------------------------
# - Submapa Passthrough
# ---------------------------------------------------------------------------------------------------
$sp = ($sm Passthrough)
bindd = $mainMod, escape, Acceder al submapa Passthrough, submap, Passthrough

submap = Passthrough
  bindd = , escape, Salir del submapa, submap, reset
submap = reset
