name = "main"
name_pretty = "Menu principal"
fixed_order = true
icon = ""


[[entries]]
icon = ""
text = "Update"
actions = { "update" = "ghostty --class=local.floating -e paru -Syu" }

[[entries]]
icon = ""
text = "About"
actions = { "about_system" = "ghostty --class=local.floating -e $SHELL -c 'fastfetch;read -n 1 -s;exit'" }

[[entries]]
icon = "󰹑"
text = "Captura"
submenu = "screenshot"

[[entries]]
icon = ""
text = "Waybar"
actions = { "change_layout" = "~/.config/waybar/scripts/change_layout_uwsm.sh" }

[[entries]]
icon = ""
text = "Sistema"
submenu = "system"

[[entries]]
icon = ""
text = "Keybindings"
actions = { "keybindings" = "menubinds.sh" }

[[entries]]
icon = "󰉉"
text = "Setup"
submenu = "setup"

[[entries]]
icon = "󰊗"
text = "Juegos y otras cosas"
submenu = "games"
