## Configuracion MPV ##
## GENERAL ##
title="${media-title}"

## VIDEO ##
hwdec=vaapi
gpu-context=wayland
target-prim=auto
target-trc=auto

## AUDIO ##
audio-channels=auto
alang=es,spa,Spanish
ao=pulse
## SUBTITLES ##
slang=es,spa,Spanish
load-scripts=yes

## STREAM ##
#ytdl=yes
#ytdl-format=bestvideo[ext=webm][height<=?720]
cache=auto

input-ipc-server=/tmp/mpvsocket

# Título de ventana personalizado (ayuda a MPRIS)
title='${media-title}'

## OSC ##
#osc=yes
#osd-scale=1.5
osc = no
osd-bar=no
osd-font='JetBrainsMono Nerd Font Light'
background-color='#1e1e2e'
osd-back-color='#6c7086'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'
# Protocolo
#[protocol.http]
#profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
#profile-desc=http
#hls-bitrate=max # use max quality for HLS streams
#cache=yes
#no-cache-pause # don't pause when the cache runs low
#
#[protocol.https]
#profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
#profile-desc=https
#profile=protocol.http
#
#[protocol.ytdl]
#profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
#profile-desc=ytdl
#profile=protocol.http
