## Configuracion MPV ##
## GENERAL ##
title="${media-title}"
keep-open=yes

## VIDEO (Moderno) ##
gpu-api=vulkan
hwdec=auto-safe
gpu-context=wayland

## AUDIO ##
audio-channels=auto
alang=es,spa,Spanish
ao=pulse

## SUBTITLES ##
slang=es,spa,Spanish
sub-auto=fuzzy
load-scripts=yes

## STREAM ##
cache=auto

## INTERFAZ ##
osc=no
osd-bar=no
osd-font='Google Sans Flex'

input-ipc-server=/tmp/mpvsocket
