## Configuracion MPV ##
## GENERAL ##
title="${media-title}"

## VIDEO ##
hwdec=vaapi
gpu-context=wayland
target-prim=auto
target-trc=auto

## AUDIO ##
audio-channels=auto
alang=es,spa,Spanish
#ao=pulse
## SUBTITLES ##
slang=es,spa,Spanish

## STREAM ##
#ytdl=yes
#ytdl-format=bestvideo[ext=webm][height<=?720]
cache=auto

## OSC ##
osc=yes
osd-scale=1.5

background-color='#1e1e2e'
osd-back-color='#6c7086'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'

