animations {
    enabled = true
    bezier = customFade, 0.82, 0.00, 0.44, 0.77
    bezier = myBezier, 	0.1, 0.01, 0.38, 1.077
    animation = windows, 1, 7, myBezier
    animation = windowsIn, 1, 7, myBezier, popin
    animation = windowsOut, 1, 7, myBezier, 
    animation = fade, 1, 10, default
}
