-- Generated by Matugen
return {
    image = "/home/oscar/Imágenes/Wallpapers/wallhaven-7jjmgv.jpg",

    background = "0xff191113",

    error = "0xffffb4ab",

    error_container = "0xff93000a",

    inverse_on_surface = "0xff382e30",

    inverse_primary = "0xff8c4a5d",

    inverse_surface = "0xffefdfe1",

    on_background = "0xffefdfe1",

    on_error = "0xff690005",

    on_error_container = "0xffffdad6",

    on_primary = "0xff551d2f",

    on_primary_container = "0xffffd9e1",

    on_primary_fixed = "0xff3a071b",

    on_primary_fixed_variant = "0xff703346",

    on_secondary = "0xff422930",

    on_secondary_container = "0xffffd9e1",

    on_secondary_fixed = "0xff2b151b",

    on_secondary_fixed_variant = "0xff5b3f46",

    on_surface = "0xffefdfe1",

    on_surface_variant = "0xffd6c2c5",

    on_tertiary = "0xff472a0a",

    on_tertiary_container = "0xffffdcbf",

    on_tertiary_fixed = "0xff2d1600",

    on_tertiary_fixed_variant = "0xff61401e",

    outline = "0xff9e8c8f",

    outline_variant = "0xff514346",

    primary = "0xffffb1c5",

    primary_container = "0xff703346",

    primary_fixed = "0xffffd9e1",

    primary_fixed_dim = "0xffffb1c5",

    scrim = "0xff000000",

    secondary = "0xffe3bdc5",

    secondary_container = "0xff5b3f46",

    secondary_fixed = "0xffffd9e1",

    secondary_fixed_dim = "0xffe3bdc5",

    shadow = "0xff000000",

    source_color = "0xffee598c",

    surface = "0xff191113",

    surface_bright = "0xff413739",

    surface_container = "0xff261d1f",

    surface_container_high = "0xff312829",

    surface_container_highest = "0xff3c3234",

    surface_container_low = "0xff22191b",

    surface_container_lowest = "0xff140c0e",

    surface_dim = "0xff191113",

    surface_tint = "0xffffb1c5",

    surface_variant = "0xff514346",

    tertiary = "0xffeebd92",

    tertiary_container = "0xff61401e",

    tertiary_fixed = "0xffffdcbf",

    tertiary_fixed_dim = "0xffeebd92",

}

