-- Generated by Matugen
return {
    image = "/home/oscar/Imágenes/Wallpapers/frieren_sleeping.jpg",

    background = "0xff1a1111",

    error = "0xffffb4ab",

    error_container = "0xff93000a",

    inverse_on_surface = "0xff382e2e",

    inverse_primary = "0xff8f4a4d",

    inverse_surface = "0xfff0dede",

    on_background = "0xfff0dede",

    on_error = "0xff690005",

    on_error_container = "0xffffdad6",

    on_primary = "0xff561d22",

    on_primary_container = "0xffffdada",

    on_primary_fixed = "0xff3b080f",

    on_primary_fixed_variant = "0xff733337",

    on_secondary = "0xff44292a",

    on_secondary_container = "0xffffdada",

    on_secondary_fixed = "0xff2c1516",

    on_secondary_fixed_variant = "0xff5d3f40",

    on_surface = "0xfff0dede",

    on_surface_variant = "0xffd7c1c1",

    on_tertiary = "0xff422c05",

    on_tertiary_container = "0xffffddb1",

    on_tertiary_fixed = "0xff291800",

    on_tertiary_fixed_variant = "0xff5c421a",

    outline = "0xff9f8c8c",

    outline_variant = "0xff524343",

    primary = "0xffffb3b5",

    primary_container = "0xff733337",

    primary_fixed = "0xffffdada",

    primary_fixed_dim = "0xffffb3b5",

    scrim = "0xff000000",

    secondary = "0xffe6bdbd",

    secondary_container = "0xff5d3f40",

    secondary_fixed = "0xffffdada",

    secondary_fixed_dim = "0xffe6bdbd",

    shadow = "0xff000000",

    source_color = "0xff6b4748",

    surface = "0xff1a1111",

    surface_bright = "0xff413737",

    surface_container = "0xff271d1d",

    surface_container_high = "0xff322828",

    surface_container_highest = "0xff3d3232",

    surface_container_low = "0xff221919",

    surface_container_lowest = "0xff140c0c",

    surface_dim = "0xff1a1111",

    surface_tint = "0xffffb3b5",

    surface_variant = "0xff524343",

    tertiary = "0xffe6c18d",

    tertiary_container = "0xff5c421a",

    tertiary_fixed = "0xffffddb1",

    tertiary_fixed_dim = "0xffe6c18d",

}

