# █░█ █▄█ █▀█ █▀█ █░░ ▄▀█ █▄░█ █▀▄
# █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▀█ █░▀█ █▄▀

# --- VARIABLES ---
$mainMod = SUPER
$terminal = uwsm app -- xdg-terminal-exec
$fileManager = $terminal -e yazi
$browser = firefox
$emacs = emacsclient -c -a 'emacs'

# Carga de configuraciones de menús/lanzadores
source = ~/.config/hypr/configs/walker_menu.conf

# --- ENTORNO Y SEGURIDAD ---
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/permissions.conf
source = ~/.config/hypr/configs/plugins.conf
exec-once = hyprpm reload # Carga de plugins si es necesario

# --- HARDWARE & MONITORES ---
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/devices.conf
source = ~/.config/hypr/configs/gestures.conf

# --- ESTÉTICA & COLORES ---
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/configs/appearance.conf
source = ~/.config/hypr/configs/animation.conf

# --- REGLAS DE VENTANAS Y CAPAS ---
# Nota: La regla del dashboard de AGS está en layerrules.conf
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/layerrules.conf

# --- FUNCIONALIDAD & ATAJOS ---
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/auto-exec.conf

# --- OTROS ---
source = ~/.config/hypr/configs/miscelanea.conf
