$mainMod = SUPER
$terminal = uwsm app -- xdg-terminal-exec
$fileManager = thunar
$menu = walker
$browser = firefox
$emacs = emacsclient -c -a 'emacs'

#$fileManager = $emacs --eval '(dired default-directory)'
source = colors.conf
#source = ~/.config/hypr/mocha.conf
exec-once = hyprpm reload # En caso de usar plugins

source = ~/.config/hypr/configs/plugins.conf
source = ~/.config/hypr/configs/animation.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/appearance.conf
source = ~/.config/hypr/configs/miscelanea.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/auto-exec.conf
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/layerrules.conf
source = ~/.config/hypr/configs/devices.conf
source = ~/.config/hypr/configs/gestures.conf
source = ~/.config/hypr/configs/permissions.conf

#source = ./dms/cursor.conf
#source = ./dms/binds.conf