text = rgb(dfe4dd)
accent = rgb(95d5a8)
alternate_base = rgb(0f1511)
bright_text = rgb(dfe4dd)
accent_secondary = rgb(b6ccb9)
base = rgb(0f1511)
font_family = Google Sans Flex
font_family_monospace = JetBrains Mono
icon_theme = Papirus Dark