general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita iniciar múltiples instancias de hyprlock.
    before_sleep_cmd = loginctl lock-session    # Bloquea la pantalla antes de suspender.
    after_sleep_cmd = hyprctl dispatch dpms on  # Evita tener que pulsar una tecla dos veces para encender la pantalla.
}

# CONTROLES DE LA PANTALLA PRINCIPAL
listener {
    timeout = 150                               # 2.5 min.
    on-timeout = brightnessctl --save && brightnessctl set 10% # Guarda el brillo actual y lo baja al 10% (seguro para OLED).
    on-resume = brightnessctl --restore        # Restaura el brillo original al detectar actividad.
}

# CONTROLES DEL TECLADO CORREGIDOS
listener { 
    timeout = 150                               # 2.5 min.
    on-timeout = brightnessctl --device="asus::kbd_backlight" --save && brightnessctl --device="asus::kbd_backlight" set 0 # Guarda y apaga el teclado.
    on-resume = brightnessctl --device="asus::kbd_backlight" --restore # Restaura el brillo del teclado.
}

# BLOQUEO DE PANTALLA
listener {
    timeout = 300                               # 5 min.
    on-timeout = loginctl lock-session            # Bloquea la sesión actual.
}

# APAGADO DE PANTALLA (DPMS)
listener {
    timeout = 330                               # 5.5 min.
    on-timeout = hyprctl dispatch dpms off        # Apaga la señal de la pantalla.
    on-resume = hyprctl dispatch dpms on          # Enciende la pantalla al detectar actividad.
}

# SUSPENSIÓN DEL EQUIPO
listener {
    timeout = 1800                              # 30 min.
    on-timeout = systemctl suspend                # Suspende el PC.
}
