source = ~/.config/hypr/colors.conf
$font = Google Sans Flex
$monofont = GeistMono Nerd Font
general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
    disable_loading = true
}
background {
    monitor = 
    path = $image
    blur_passes = 3
    blur_size = 8
    noise = 0.01
    contrast = 0.8920
    vibrancy_darkness = 0.06
    brightness = 0.8160
}

input-field {
    monitor = 
    size = 300,60
    outline_thickness = 3
    dots_size = 0.33 
    dots_spacing = 0.15 
    dots_center = true
    outer_color = $outline
    inner_color = $background
    font_color = $on_background
    fade_on_empty = false
    placeholder_text = <i>Introduce contraseña...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor = 
    text = <b>$TIME</b>
    color = $primary_fixed
    font_size = 120
    font_family = $font
    position = 0, 500
    halign = center
    valign = center
}
label {
    text = cmd[update:1000] echo "$(date +"%A, %d de %B de %Y")"
    color = $primary_fixed
    font_size = 25
    font_family = $font
    position = 0, 390
    halign = center
    valign = center
}
image {
    monitor = 
    path = ~/.face
    size = 120
    rounding = -1
    border_color = $primary
    halign = center
    valign = center
    position = 0,90
    rotate = 0
    reload_time = -1
}

label {
    text = cmd[update:1000] echo -e "$(~/.config/hypr/scripts/battery-infolock.sh)"
    font = $monofont
    position = -30, -30
    font_size = 20
    halign = right
    valign = top
}
label {
    monitor =
    # Actualiza cada segundo para seguir la canción
    text = cmd[update:1000] echo "<b>$(~/.config/hypr/scripts/hyprlock-music.sh --title)</b>"
    color = rgb(255,255,255)
    font_size = 18
    font_family = $font    
    position = -138, -36
    halign = center
    valign = top
}
label {
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/hyprlock-music.sh --status)"
    font = $monofont
    position = 140, -30
    halign = center
    valign = top
    font_size = 30
    onclick = playerctl play-pause
}
label {
    text = 󰒭
    font = $monofont
    position = 90, -30
    font_size = 30
    halign = center
    valign = top
    onclick = playerctl previous
}

label {
    text = 󰒮
    font = $monofont
    font_size = 30
    position = 190, -30
    halign = center
    valign = top
    onclick = playerctl next
}

label {
    text = cmd[update:0] echo "<i>$(hyprctl splash)</i>"
    color = $on_background
    font_size = 20
    font_family = $font
    italic = true

    position = 0, 80
    halign = center
    valign = bottom
}

