theme {
    icon_theme = Papirus-Dark
    style = kvantum
    font = Google Sans Flex
    color_scheme = /home/oscar/.local/share/color-schemes/noctalia.colors.colors
    font_fixed = Geist Mono Nerd Font
    font_size = 12
    font_fixed_size = 12
}
