text = rgb(f1dfdb)
accent = rgb(ffb4a3)
alternate_base = rgb(1a110f)
bright_text = rgb(f1dfdb)
accent_secondary = rgb(e7bdb3)
base = rgb(1a110f)
font_family = Google Sans Flex
font_family_monospace = JetBrains Mono
icon_theme = Papirus Dark