text = rgb(f1dfd9)
accent = rgb(ffb59a)
alternate_base = rgb(1a110e)
bright_text = rgb(f1dfd9)
accent_secondary = rgb(e7beaf)
base = rgb(1a110e)
font_family = Google Sans Flex
font_family_monospace = JetBrains Mono
icon_theme = Papirus Dark