source = $HOME/.config/hypr/colors.conf
$accent = $primary
$accentAlpha = $primary
$font = JetBrainsMono Nerd Font Propo

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $image
  blur_passes = 4
  color = $background
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = $invert_primary
  font_size = 25
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# TIME
label {
  monitor =
  text = $TIME
  color = $invert_primary
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:30000] date +"%A, %d %B %Y"
  color = $invert_primary
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}
# Information
label {
    monitor =
    text = cmd[update:1000] echo -e "$(~/.config/hypr/scripts/battery-infolock.sh)"
    color = $invert_primary
    font_size = 30
    font_family = $font
    position = -20, -20
    halign = center
    valign = top
}
# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface
  font_color = $inverse_surface
  fade_on_empty = false
  placeholder_text = <i>󰌾 Sesion iniciada como </i>$USER
  hide_input = false
  check_color = $accent
  fail_color = $error
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $inverse_primary
  position = 0, -47
  halign = center
  valign = center
}
