# Configuración global
max-gamma = 1.0

# Perfil de día (Luz natural)
profile {
    time = 08:00
    identity = true
}

# Perfil de tarde (Empieza el descanso visual)
profile {
    time = 19:30
    temperature = 4500
    gamma = 0.9
}

# Perfil de noche (Protección total)
profile {
    time = 22:30
    temperature = 3800
    gamma = 0.8
}
