$menu_dir = ~/.config/rofi/scripts
$menu = $menu_dir/launcher.sh
$bar_layout_selector = $menu_dir/waybar-selector.sh
$wallpaper_selector = $menu_dir/wallSelect.sh
$emoji_menu = rofimoji --prompt "Emojis:" --action copy
$menu_layout_changer = $menu_dir/rofi-launcher-layout-pick.sh
$clipboard_menu = cliphist list | rofi -dmenu -display-columns 2 -p "Portapapeles:" | cliphist decode | wl-copy
$system_menu = $menu_dir/system-menu.sh
bind = SUPER, C, exec, rofi -show calc -modi calc -no-show-match -no-sort
