[Unit]
Description=Emacs text editor
Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/
After=graphical-session.target
Slice=background-graphical.slice

[Install]
WantedBy=graphical-session.target
