# : Manager [[[

[manager]
cwd = { fg = "#eedfe3" }

# Tab
tab_active = { fg = "#531d39", bg = "#feb0d2", bold = true }
tab_inactive = { fg = "#ffd8e6", bg = "#380723" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff9d60", bg = "#ff9d60" }
marker_cut = { fg = "#ffdcc6", bg = "#ffdcc6" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f2bb98", bg = "#f2bb98" }

# Count
count_copied = { fg = "#301401", bg = "#ffdcc6" }
count_cut = { fg = "#301401", bg = "#ffdcc6" }
count_selected = { fg = "#531d39", bg = "#f2bb98" }

# Border
border_symbol = "│"
border_style  = { fg = "#feb0d2" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#531d39", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#feb0d2", fg = "#531d39", bold = true }
normal_alt  = { bg = "#504348", fg = "#d4c2c7" }

# Select mode
select_main = { bg = "#e0bdca", fg = "#412a34", bold = true }
select_alt  = { bg = "#504348", fg = "#d4c2c7" }

# Unset mode
unset_main = { bg = "#f2bb98", fg = "#49280f", bold = true }
unset_alt  = { bg = "#504348", fg = "#d4c2c7" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#feb0d2", bg = "#40373a" }
progress_error = { fg = "#ffb4ab", bg = "#40373a" }

# Permissions
permissions_t = { fg = "#af5576" }
permissions_w = { fg = "#d6641b" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff7e2d" }
permissions_s = { fg = "#ff3f84" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#feb0d2" }
active = { fg = "#f2bb98", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#feb0d2" }
value = { fg = "#eedfe3" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#feb0d2", bg = "#531d39" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#feb0d2" }
title = {}
hovered = { fg = "#ffdcc6", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#40373a" }
cand = { fg = "#feb0d2" }
rest = { fg = "#531d39" }
desc = { fg = "#eedfe3" }
separator = " ▶ "
separator_style = { fg = "#eedfe3" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eedfe3" }
run = { fg = "#eedfe3" }
footer = { fg = "#412a34", bg = "#e0bdca" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f2bb98" }
title_warn = { fg = "#feb0d2" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eedfe3" },
    { name = "*/", fg = "#feb0d2" },
]

# : ]]]