force_keyboard_focus = true   # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
click_to_close = true           # closes walker if clicking outside of the main content area
selection_wrap = true          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
exact_search_prefix = "'"       # disable fuzzy searching
theme = "matugen"
app_launch_prefix = "uwsm app -- "
hide_action_hints = false       # globally hide the action hints
hide_action_hints_dmenu = true  # hide the actions hints for dmenu
resume_last_query = false # open walker with the last query in place
hide_quick_activation = true
[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[columns]
"symbols" = 1

[placeholders]
"default" = { input = "Buscar...", list = "Sin Resultados" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[providers]
max_results = 256
default = [
  "desktopapplications",
  "calc",
  "websearch",
  "windows",	
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date

[providers.actions] # This will be MERGED/OVEWRITTEN with what the user specifies
dmenu = [{ action = "select", default = true, bind = "Return" }]

[providers.sets.hyprsphere]
default = [
  "menus:main",
  "menus:keybinds",
  "menus:themes",
  "menus:power-profiles",
  "menus:fastfetch",
  "menus:waybar-layout-selector",
  "menus:system",
  "menus:screenshot",
  "menus:setup",
]
empty = ["menus:main"]

[[emergencies]]
text = "Reinciar walker"
command = "killall -9 walker && walker --gapplication-service & disown"

[[emergencies]]
text = "Reiniciar elephant"
command = "systemctl restart --user elephant"
