general { 
    gaps_in = 8
    gaps_out = 12
    border_size = 2
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $primary $tertiary 45deg
    col.inactive_border = $surface

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true
    resize_corner = 3
    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
    layout = dwindle
    #layout = nstack
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 13
    rounding_power = 2
    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.92
	

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 2
        
        vibrancy = 0.1695
    }
    shadow {
	   enabled = true
	   range = 4
           render_power = 3
           color = $shadow
	}
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
   new_status = master
}
