exec-once = /usr/bin/emacs --daemon &
exec-once = waybar -s ~/.config/waybar/style-hypr.css -c ~/.config/waybar/config-hypr.jsonc
exec-once = swww-daemon
exec-once = swayosd-server
#exec-once = swww img Imágenes/Wallpapers/91672148_p0.jpg
#exec-once = waytrogen --restore &
exec-once = udiskie &
#exec-once = hyprpaper &
#exec-once = swww img ~/Bildoj/Wallpapers/wallpaperflare.com_wallpaper3.jpg
#exec-once = waybar & hyprpaper & firefox
exec-once = swaync
exec-once = hypridle
exec-once= /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#exec-once = /usr/libexec/hyprpolkitagent
#exec-once = nmapplet &
#exec-once = wlsunset -s 18:06
