#exec-once = uwsm app -- ~/.config/waybar/scripts/launch.sh
#exec-once = swww-daemon
#exec-once = swayosd-server
#exec-once = /usr/bin/emacs --daemon &
exec-once = uwsm app -- udiskie &
#exec-once = emacs --fg-daemon
#exec-once = uwsm app -- swaync
#exec-once = uwsm app -- hypridle
#exec-once = uswm app -- /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = uwsm app -- kanshi &
exec-once = emacs --fg-daemon
exec-once = pypr
