exec-once = emacs --daemon
exec-once = waybar -s ~/.config/waybar/style-hypr.css -c ~/.config/waybar/config-hypr.jsonc
exec-once = swww-daemon
exec-once = ags &
#exec-once = swww restore
exec-once = waypaper --restore
exec-once = udiskie -t &
#exec-once = swww img ~/Bildoj/Wallpapers/wallpaperflare.com_wallpaper3.jpg
# exec-once = waybar & hyprpaper & firefox
exec-once = swaync
exec-once = hypridle
exec-once= /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#exec-once = nmapplet &
