-- configs/auto-exec.lua
hl.on("hyprland.start", function()
    hl.exec_cmd("udiskie &")
    hl.exec_cmd("qs -d")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    --hl.exec_cmd("emacs --fg-daemon")
    hl.exec_cmd("trash-empty 30")
    hl.exec_cmd("snappy-switcher --daemon")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("xhost +SI:localuser:root")
    --hl.exec_cmd("awww-daemon &")
    --hl.exec_cmd("swayosd-server &")
    --hl.exec_cmd("hypridle &")
    --hl.exec_cmd("systemctl start --user elephant") 
  end)
hl.on("monitor.added", function ()
    hl.exec_cmd("awww img"..Colors.image)
    --hl.exec_cmd("launch_waybar")
end)

