# ~/.config/hypr/configs/keybinds.conf

# ╔═════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                     Configuración de Atajos                                     ║
# ╚═════════════════════════════════════════════════════════════════════════════════════════════════╝

# ---------------------------------------------------------------------------------------------------
# - Definición de la tecla Mod principal
# ---------------------------------------------------------------------------------------------------
$mainMod = SUPER

# ---------------------------------------------------------------------------------------------------
# - Carga de archivos de atajos de teclado
# ---------------------------------------------------------------------------------------------------
$sm = Submap
source = ./keybinds/apps.conf
source = ./keybinds/windows.conf
source = ./keybinds/workspaces.conf
source = ./keybinds/media.conf
source = ./keybinds/system.conf

# ---------------------------------------------------------------------------------------------------
# - Limpieza de variables temporales
# ---------------------------------------------------------------------------------------------------
$sm=#!
$sp = #!
$sr = #!
$d = #!
