# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█
# ============================================================
# LAYER RULES (Sintaxis Estricta match:namespace)
# ============================================================

# --- LANZADORES (Rofi, Walker) ---
layerrule {
    name = launchers
    match:namespace = ^(rofi|walker)$
    blur = on
    # La Wiki sustituye ignorezero por ignore_alpha (0.0 ignora píxeles totalmente transparentes)
    ignore_alpha = 0.5
    animation = popin 95%
}

# --- BARRA DE ESTADO (Waybar) ---
layerrule {
    name = status-bar
    match:namespace = ^(waybar)$
    blur = on
    ignore_alpha = 0.1
    no_anim = on
}


# --- MENÚ DE SALIDA (Wlogout) ---
layerrule {
    name = logout-menu
    match:namespace = logout_dialog
    blur = on
    animation = fade
    ignore_alpha = 0.5
}

# --- INTERFAZ DE SISTEMA (SwayOSD) ---
layerrule {
    name = osd-visuals
    match:namespace = ^(swayosd)$
    no_anim = on
    blur = on
    ignore_alpha = 0.5
#    animation = popin 80%
}

# --- NOTIFICACIONES (SwayNC) ---
# He reactivado estas reglas adecuándolas a la sintaxis correcta
layerrule {
    name = notification-center
    match:namespace = swaync-notification-window
    no_anim = on
    blur = on
    ignore_alpha = 0.5
}

layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-control-center, blur on
