# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█
layerrule = blur,rofi
layerrule = ignorezero,rofi
#layerrule = noanim,swaync-notification-window
#layerrule = ignorezero,swaync-notification-window
layerrule = blur, waybar
layerrule = blur, wleave
layerrule = noanim, wleave
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.45, waybar
layerrule = noanim,walker
layerrule = ignorezero,walker
layerrule = noanim,swayosd
