permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/grim, screencopy, allow
permission = .*hyprexpo\.so$, plugin, allow
permission = .*dynamic-cursors\.so$, plugin, allow
permission = .*hyprlock.*$, screencopy, allow
permission = .*, keyboard, allow
permission = /usr/bin/hyprpicker, screencopy, allow
permission = .*quickshell.*$, screencopy, allow

