permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/grim, screencopy, allow
permission = /usr/bin/hyprshot, screencopy, allow
permission = .*hyprexpo\.so$, plugin, allow
permission = .*hyprlock.*$, screencopy, allow
permission = .*, keyboard, allow
#permission = at-translated-set-2-keyboard, keyboard, allow
#permission = asue140d:00-04f3:31b9-keyboard, keyboard, allow
#permission = asus-wmi-hotkeys, keyboard, allow
#permission = asus-numpad, keyboard, allow

