$menu = walker
$bar_layout_selector = walker -m menus:waybar-layout-selector
$wallpaper_selector = walker -m menus:wallpapers #waypaper
$emoji_menu = walker -m symbols
$menu_layout_changer = walker
$clipboard_menu = walker -m clipboard
$system_menu = walker -s hyprsphere
