source = ~/.config/hypr/configs/rules_windows/btop.conf
## Ventanas a espacios de trabajo
windowrule = match:class ^(vesktop)$, workspace 5
windowrule = match:class ^(gimp)$, workspace 4


windowrule = match:class ^(mpv)$, float on
windowrule = match:class ^(mpv)$, center on
windowrule = match:class ^(mpv)$, size 900 500

# Browser Picture in Picture
source = ~/.config/hypr/configs/rules_windows/PictureInPicture.conf
windowrule {
    name = floating-utils
    match:class = ^(blueberry.py|nm-applet|kvantummanager|.*dialog.*|org.localsend.localsend_app)$
    match:title = ^(Acerca.*|Watering)$
    float = on
    center = on
}


windowrule = float on,match:class ^(.*Cartridges)$
windowrule = size 35% 50%, match:class xdg-desktop-portal-gtk
windowrule = float on,match:class ^(xdg-desktop-portal-gtk)$
source = ~/.config/hypr/configs/rules_windows/jetbrains.conf
source = ~/.config/hypr/configs/rules_windows/terminals.conf

# FIxing Xwayland things
source = ~/.config/hypr/configs/rules_windows/someFixes.conf
source = ~/.config/hypr/configs/rules_windows/steam.conf


windowrule {
    name = tag-floating-term
    match:tag = floating-term
    float = on
    center = on
    size = 800 700
}

# Reglas para el tag 'floating-window'
windowrule {
    name = tag-floating-window
    match:tag = floating-window
    float = on
    center = on
    size = 900 800
}

# ============================================================
# ASIGNACIÓN DE TAGS (Static Rules)
# ============================================================

# Asignación a terminales flotantes
windowrule = tag +floating-term, match:class ^(local\.floating)$

# Asignación a utilidades gráficas (Usando RegEx agrupado según la Wiki)
windowrule = tag +floating-window, match:class ^(xdg-desktop-portal-gtk|imv|.*Showtime|.*Cartridges|nwg-look|qt5ct|qt6ct|com.github.rafostar.Clapper|pavucontrol|waypaper|waifudownloader|catgirldownloader|com.gabm.satty)$

# ============================================================
# REGLAS ESPECÍFICAS Y EXCEPCIONES
# ============================================================

# Galculator: Ajuste de tamaño específico
windowrule {
    name = calculator-fix
    match:class = ^(galculator)$
    float = on
    size = 100 200
}

# Quickshell
windowrule = match:class ^(org\.quickshell)$, float on

# Opacidad Dinámica (La Biblia: 'floating' y 'focus' son props booleanos)
# "Set active and inactive opacity respectively"
# windowrule {
#     name = dynamic-opacity
#     match:float = false
#     match:focus = false
#     opacity = 0.9 0.9 override
# }

workspace = 2, layoutopt:direction:right
