windowrulev2 = nomaxsize, title:^(Wine-agordo)$

windowrulev2 = float, center, title:^(emacs-run-launcher)$

windowrulev2 = float, center, class:^(imv)$

windowrulev2 = center, title:^(emacs-run-launcher)$


#windowrulev2 = move 100 100, float, class:.* # You'll probably like this.
$center-float-title = title:^(.*Open Folder.*)$|^(.*Open File.*)$|^(.*Save File.*)$|^(.*Save Folder.*)$|^(.*Save Image.*)$|^(.*Save As.*)$|^(.*Open As.*)$

windowrule = float, nwg-look|qt5ct|qt6ct|mpv|waypaper

windowrulev2=float, title:^(VortaroES)$
windowrulev2=float, title:^(Bildo en bildo)$

