windowrule = float, center, title:^(emacs-run-launcher)$
windowrule = float, center, class:^(imv)$
#windowrulev2 = fullscreen,class:^(emacs)$
windowrule = center, title:^(emacs-run-launcher)$
windowrule = float, class:^(float_kitty)$
windowrule = size 800 700, class:^(float_kitty)$
## Ventanas a espacios de trabajo
windowrule = workspace 5, class:^(vesktop)$
windowrule = workspace 4, class:^(gimp)$
windowrulev2 = pseudo, class:^(org.pwmt.zathura)$
windowrulev2 = float, class:^(nwg-look|qt5ct|qt6ct|com.github.rafostar.Clapper|galculator|pavucontrol)$
windowrulev2 = float,class:^(mpv|waypaper)$
# Browser Picture in Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture in Picture)$
windowrulev2 = float, title:^(Picture in Picture)$
windowrulev2 = pin, title:^(Picture in Picture)$
#windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$
windowrulev2 = float, title:^(Acerca.*)$
windowrulev2 = float, title:^(Watering)$
windowrulev2 = size 863 639 class:^(Watering)$
windowrule = float,title:^(Progreso de las operaciones de archivo)$
windowrule = float,class:^(blueberry.py)$
windowrule = float,class:^(nm-applet)$
windowrule = float,class:^(nm-connection-editor)$
windowrule = float,class:^(kvantummanager)$
windowrule = float,class:^(nwg-displays)$
windowrule = float,class:^(.*dialog.*)$
windowrule = float,class:^(org.localsend.localsend_app)$
windowrulev2 = float,class:^(.*Loupe|.*Showtime|.*Cartridges)$
windowrulev2 = float,class:xdg-desktop-portal-gtk
windowrule = size 35% 50%, class:xdg-desktop-portal-gtk
# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█
layerrule = blur,rofi
layerrule = ignorezero,rofi
#layerrule = blur,swaync-notification-window
#layerrule = ignorezero,swaync-notification-window
layerrule = blur, waybar
layerrule = blur, wleave
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.5, waybar
layerrule = noanim,walker
layerrule = ignorezero,walker
# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix focus issues when dialogs are opened or closed
# windowrulev2 = windowdance,class:^(jetbrains-.*)$,floating:1
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrulev2 = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1

#! Center popups/find windows
#windowrulev2 = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
#! Enabling this makes it impossible to provide input to any popup dialogue (search window, new file, etc.)
#windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
#windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
#! Disable window flicker when autocomplete or tooltips appear
#windowrulev2 = noinitialfocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1
windowrulev2=noinitialfocus,class:^jetbrains-.*$,floating:1,title:^$|^\s$|^win\d+$
windowrulev2 = noinitialfocus, class:^jetbrains-.*$, floating:1, title:^$|^\s$|^win\d+$
# -- End of IntelliJ Rules --


# FIxing Xwayland things
windowrulev2 = noblur,class:^()$,title:^()$
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = suppressevent maximize, class:^(?!firefox).*$

## Steam window rules
# Float Steam, fullscreen RetroArch
windowrule = float, class:steam
windowrule = center, class:steam, title:Steam
windowrule = opacity 1 1, class:steam
windowrule = size 1100 700, class:steam, title:Steam
windowrule = size 460 800, class:steam, title:Friends List
windowrule = idleinhibit fullscreen, class:steam
