# // █▀▄ █▀▀ █▀▀ ▄▀█ █░█ █░░ ▀█▀
# // █▄▀ ██▄ █▀░ █▀█ █▄█ █▄▄ ░█░
$WORKFLOW = default
$WORKFLOW_ICON = 
$WORKFLOW_DESCRIPTION = Default HyDE configuration // Disables workflow overrides
$WORKFLOW_ICON=
$WORKFLOW_DESCRIPTION = Unset workflow configuration
