#+title: Configuraciones
#+author: Mester
#+description: configuración de emacs
#+property: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+auto_tangle: t

* Comienzo del fichero
** Añadiendo lexical binding
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src
* Configuraciones básicas
** Añadir ruta al directorio de carga
Esto es para hacer que algunos scripts de uso propio sean utilizables
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src
** Elpaca
El gestor de paquetes que utilizo, junto con lo necesario para instalarlo si no esta.
#+begin_src emacs-lisp
(defvar elpaca-installer-version 0.11)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:
;;(use-package general :demand t)
;;(elpaca-wait)

;;Turns off elpaca-use-package-mode current declartion
;;Note this will cause the declaration to be interpreted immediately (not deferred).
;;Useful for configuring built-in emacs features.
;;(use-package emacs :elpaca nil :config (setq ring-bell-function #'ignore))

;; Don't install anything. Defer execution of BODY
;;(elpaca nil (message "deferred"))
#+end_src
** Apariencia
*** Tema visual
**** Tema Catppuccin
El tema visual a utilizar estando disponible aqui la configuracion
#+begin_src emacs-lisp
    (use-package catppuccin-theme
        :init
          (load-theme 'catppuccin t))
#+end_src
**** Tema ef
#+begin_src emacs-lisp :tangle no
  (use-package ef-themes
    :ensure t
    :config
    (load-theme 'ef-cherie :no-confirm))
#+end_src
*** Ajustes de fuentes y alguna cosa
#+begin_src emacs-lisp
(set-face-attribute 'default nil
  :font "Jetbrains Mono"
  :height 102
  :weight 'medium)
(set-face-attribute 'variable-pitch nil
  :font "Ubuntu"
  :height 110
  :weight 'medium)
(set-face-attribute 'fixed-pitch nil
  :font "Jetbrains Mono"
  :height 102
  :weight 'medium)
;; Makes commented text and keywords italics.
;; This is working in emacsclient but not emacs.
;; Your font must have an italic face available.
(set-face-attribute 'font-lock-comment-face nil
  :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil
  :slant 'italic)

;; This sets the default font on all graphical frames created after restarting Emacs.
;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
;; are not right unless I also add this method of setting the default font.
(add-to-list 'default-frame-alist '(font . "JetBrains Mono NerdFont-10"))

;; Uncomment the following line if line spacing needs adjusting.
(setq-default line-spacing 0.3)
#+end_src
*** Opacidad
Esta es la opacidad que el editor aplica por defecto
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 92)) ; For all new frames henceforth
#+end_src
*** Electric pair
#+begin_src emacs-lisp
(electric-pair-mode t)
#+end_src
** Configuración de IRC
Configuracion del cliente erc
#+BEGIN_SRC emacs-lisp
(setq erc-nick "mester")
(setq erc-prompt-for-password (string-trim (shell-command-to-string "cat ~/Descargas/Conjuntos\ contraseña/password_irc")))
(setq erc-track-enable-keybindings t)
(setq erc-fill-column 120
      erc-fill-function 'erc-fill-static
      erc-fill-static-center 20)
#+END_SRC
** Configuraciones personales varias
Añadiendo ajustes como mi nombre completo, desactivando barra de herramientas y otras cosas
#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Oscar")
    (setq inhibit-startup-message t
          use-short-answers t
  	      blink-matching-parent t)
      (tool-bar-mode -1)                                            ; Desactivar la barra de herramientas
      (menu-bar-mode -1)                                            ; Desactivar la barra de menús
      (scroll-bar-mode -1)                                          ; Desactivar la barra de desplazamiento visible
      (tooltip-mode -1)
      (set-fringe-mode 10)        ; Give some breathing room
     (add-to-list 'default-frame-alist '(fullscreen . maximized))
  (setq use-dialog-box nil)
  #+end_src
*** Configuracion zoom
La configuracion de los atajos de zoom
#+begin_src emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
#+end_src
*** Ubicacion custom file
#+begin_src emacs-lisp
(setq custom-file (locate-user-emacs-file "custom-vars.el"))
(load custom-file 'noerror 'nomessage)
#+end_src
*** Configuraciones diversas
Aquí se tratan configuraciones especificas útiles para diversos aspectos
**** Formato hora
Configura el formato de la hora
#+name: formato hora
#+begin_src emacs-lisp :tangle no
  display-time-24hr-format t             ; Muestra el reloj en formato 24 hrs
  display-time-format "%H:%M"             ; Le da formato a la hora
#+end_src
**** Archivos de bloqueo
Impide la creación de ficheros de bloqueo que a veces son muy coñazo al menos para mi
#+name: lock config
#+begin_src emacs-lisp :tangle no
create-lockfiles nil                    ; Impido la creación de ficheros .#
#+end_src
**** Deshabilitar sistema de auto guardado propio
Este sistema de auto guardado es muy coñazo por los archivos que genera así que lo quito, y lo cambio por [[*Supersave][SuperSave]]
#+name: native auto save
#+begin_src emacs-lisp :tangle no
auto-save-default nil                   ; Deshabilita #file#
#+end_src
**** Archivos de copia de seguridad
Configura la creación de archivos de backup para mantener las cosas más simples y practicas
#+name: backup
#+begin_src emacs-lisp :tangle no
make-backup-files nil                   ; No realiza backups de ficheros
#+end_src
**** Estableciendo configuraciones
#+begin_src emacs-lisp :noweb yes
  (setq
   <<formato hora>>
   <<native auto save>>
   load-prefer-newer t                     ; Prefiere la versión más reciente de un archivo.
   select-enable-clipboard t               ; Sistema de fusión y portapapeles de Emacs.
   vc-follow-symlinks t                    ; Siempre sigue los enlaces simbólicos.
   <<backup>>
  ;; org-footnote-section "Referencias:"  ; cambio footnotes por referencias
   ;; global-hl-line-mode t                ; Highlight current line
   kill-ring-max 128                       ; Longitud máxima del anillo de matar
   <<lock config>>
   )
 #+end_src
*** Uso de la tecla escape pues para el escape
O algo asi
#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src
** Configuración del calendario
Ajustes del calendario dias de la semana, meses los festivos y otros ajustes del calendario. 📆
#+begin_src emacs-lisp
(setq calendar-month-name-array
      ["Enero" "Febrero" "Marzo" "Abril" "Mayo" "Junio"
       "Julio"    "Agosto"   "Septiembre" "Octubre" "Noviembre" "Diciembre"])

(setq calendar-day-name-array
      ["Domingo" "Lunes" "Martes" "Miércoles" "Jueves" "Viernes" "Sábado"])

(setq org-icalendar-timezone "Europe/Madrid") ;; timezone
(setq calendar-week-start-day 1) ;; la semana empieza el lunes
;;(setq european-calendar-style t) ;; estilo europeo
(setq iso-calendar-style t) ;; formato ISO
(setq calendar-holidays '((holiday-fixed 1 1 "Año nuevo")
			  (holiday-fixed 5 17 "Dia de las letras gallegas")
			  (holiday-fixed 10 12 "Día de la Hispanidad")
			  (holiday-fixed 11 01 "Todos los Santos")
			  (holiday-fixed 12 06 "Constitución")
			  (holiday-fixed 3 28 "Reconquista de Vigo")
			  (holiday-fixed 5 1 "Dia del Trabajo")
			  (holiday-fixed 12 24 "Nochebuena")
			  (holiday-fixed 12 25 "Navidad")))
#+end_src
** Ajustes de rendimiento
Sirve para optimizar cosas en relación al rendimiento
#+begin_src emacs-lisp
(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 4 1024 1024))
;; Garbage collector optimization
(setq gcmh-idle-delay 5)
(setq gcmh-high-cons-threshold (* 1024 1024 1024))
(setq comp-deferred-compilation t)
(setq comp-async-jobs-number 8)
#+end_src
* Funciones propias
** Recargar la configuración
Esta función sirve para recargar la configuracion activa sin cerrar Emacs, no funciona
en todos los casos hay veces que hay que cerrar el programa
#+begin_src emacs-lisp
(defun os/reload-config ()
  "Recargar configuracion Emacs"
  (interactive)
  (load-file (expand-file-name "init.el" user-emacs-directory))
  (ignore (elpaca-process-queues)))
(global-set-key (kbd "C-c r") 'os/reload-config)
#+end_src
** Abrir configuración
Abrir el archivo de configuración usado en este caso abro el README.org que se edita para obtener el archivo de configuracion
#+begin_src emacs-lisp
(defun os/open-config ()
  "Abrir configuracion de emacs"
  (interactive)
  (find-file "~/.config/emacs/README.org"))
(global-set-key (kbd "C-x c") 'os/open-config)
#+end_src
** Dictionary Switcher
Función propia para cambiar entre mis diccionarios más usados
#+begin_src emacs-lisp
(defun dictionary-switcher()
  "Cambiar entre los diccionarios de Español, Esperanto e Ingles mediante un menu interactivo solo entre esos y solo a un diccionario distinto al seteado."
  (interactive)
  (let* ((dic ispell-current-dictionary)
         (change
	  (completing-read "Seleccione el diccionario a usar: " '("eo" "es_ES" "en_US") nil t)))
    (unless (string= dic change)
      (ispell-change-dictionary change)
      (message "Diccionario cambiado desde %s a %s" dic change))))
#+end_src
** Toggle webserver
Activa un servidor web con auto refresco
#+begin_src emacs-lisp
(defun toggle-webserver ()
"Function to toggle a not much bigger webserver ChatGPT helping me to fix some things
This function allow to activate the webserver when you use but if there is a process of webserver the function kill it"
   (interactive)
   (let ((proc (get-process "webserver")))
         (if (and proc (eq (process-status proc) 'run))  ;; Verifica si el proceso está corriendo
             (progn
                (delete-process "webserver")
                (message "Webserver stopped"))
                (make-process :name "webserver" :command '("npx" "browser-sync" "start" "--server" "--files" "**/*") :buffer "*webserver*" :filter (lambda (_proc output)
                 (when (string-match "Local: http://localhost:3000" output) ;; Verificamos a traves de la salida si el servidor ya se ha desplegado
                   (message " ✅ Webserver started")))))))
#+end_src
** Buffer temporal en modo Org
Permite crear un buffer temporal en modo org el cual puede ser usado para tomar notas temporales que no están asociadas a algún archivo útil
cuando necesitas crear notas para algo puntual simplemente organizando información pero luego no lo necesitas para nada más, también da la posibilidad de guardarlo como archivo
#+begin_src emacs-lisp
(defun org-temp-buffer ()
   "Acceder a un buffer temporal de orgmode"
   (interactive)
   (if (get-buffer "*orgtemp*")
         (switch-to-buffer "*orgtemp*")
         (switch-to-buffer (get-buffer-create "*orgtemp*"))
         (insert (format "#+title: Org Temporal Buffer\n#+description: Espacio para la toma de notas temporales\n#+author: %s\n\n" user-full-name))
         (org-mode)))
#+end_src
** Modo sin distracciones
No es mia pero es muy util ya que me permite hacerlo mucho con el tema de distracción
#+name: sin distracciones
#+begin_src emacs-lisp :tangle no
 (defun ews-distraction-free ()
  "Distraction-free writing environment using Olivetti package."
  (interactive)
  (if (equal olivetti-mode nil)
      (progn
        (window-configuration-to-register 1)
        (delete-other-windows)
        (text-scale-set 2)
        (olivetti-mode t))
    (progn
      (if (eq (length (window-list)) 1)
          (jump-to-register 1))
      (olivetti-mode 0)
      (text-scale-set 0))))
#+end_src
** Abrir dashboard
Me permite abrir el dashboard
#+name: abrir dashboard
#+begin_src emacs-lisp :tangle no
  (defun open-dashboard ()
    "Abre el buffer *dashboard* y salta al primer widget."
    (interactive)
    (delete-other-windows)
    ;; Refresca  dashboard buffer
    (if (get-buffer dashboard-buffer-name)
        (kill-buffer dashboard-buffer-name))
    (dashboard-insert-startupify-lists)
    (switch-to-buffer dashboard-buffer-name))
#+end_src
* Org Mode
** Encabezados
Esto me permite aplicar mis configuraciones de preferencia a los encabezados tengo una lista que contiene listas asociativas con la información necesaria, y aprovecho las
funciones car y cdr para extraer los múltiples objetos de esa lista con la información y ejecutar la macro custom-set-faces con la información requerida y que fue puesta en la lista
#+begin_src emacs-lisp
(dolist (item '((org-level-1 . (1.5 . outilne-1))
    		   (org-level-2 . (1.4 . outline-2))
	          (org-level-3 . (1.25 . outline-3))
                  (org-level-3 . (1.1 . outline-3))
                  (org-document-title . (1.7 . nil))))
  (custom-set-faces `( ,(car item) ((t (:inherit ,(cdr (cdr item)) :height ,(car (cdr item))))))))
#+end_src
** Ajustes generales
Ajustes de Org Mode
*** Configurar archivos
#+begin_src emacs-lisp
  (setq org-directory "~/org/")
  (setq diary-file (expand-file-name "diario.org" org-directory))
  (setq org-default-notes-file (expand-file-name "notes.org" org-directory))
  (setq org-agenda-files (list (expand-file-name "agenda.org" org-directory) (expand-file-name "proyectos.org" org-directory)))
  (setq org-archive-location "~/org/%s_archivo.org::datetree/")
#+end_src
*** Añadiendo ajustes varios
#+begin_src emacs-lisp
(setq org-export-with-drawers nil
      org-export-with-todo-keywords nil
      org-export-with-broken-links t
      org-export-with-toc nil
      org-export-with-smart-quotes t
      org-export-date-timestamp-format "%d %B %Y"
      org-list-allow-alphabetical t)

 (setq org-return-follows-link  t) ;; Hace que pulsando Enter funcione el seguir el enlace
 (require 'org-tempo)               
(use-package org
    :ensure nil)
(setq org-ellipsis "▼")
(setq-default org-startup-indented t
                    org-pretty-entities t
                    org-use-sub-superscripts "{}"
                    org-hide-emphasis-markers t
                    org-startup-with-inline-images t
                    image-actual-width '(300))
(add-hook 'org-mode-hook 'org-indent-mode)
        (global-set-key (kbd "C-c c") 'org-capture)
        (global-set-key (kbd "C-c a") 'org-agenda)
#+end_src
*** Ajustes a elementos del org-mode
#+begin_src emacs-lisp :tangle no
(add-hook 'org-mode-hook #'variable-pitch-mode)
(custom-set-faces
 ;; Código, bloques, verbatim, tablas
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-code ((t (:inherit fixed-pitch))))
 '(org-table ((t (:inherit fixed-pitch))))
 '(org-verbatim ((t (:inherit fixed-pitch))))
 '(org-formula ((t (:inherit fixed-pitch))))
 '(org-checkbox ((t (:inherit fixed-pitch))))
 ;; Estilo gris clásico para metadatos
 '(org-meta-line ((t (:inherit (shadow fixed-pitch)))))
 '(org-modern-symbol ((t (:family "Jetbrains Mono")))))
#+end_src
*** Ajustes del todo
#+begin_src emacs-lisp
(setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "WAITING(w)" "PROJ(p)" "PAUSED(P)" "|" "DONE(d)" "CANCELLED(c)")))
    (setq org-todo-keyword-faces
           '(("TODO" . "coral")
             ("NEXT" . "cyan")
             ("PROJ" . "orange")
 	       ("WAITING" . "yellow")
             ("DONE" . "green")
             ("PAUSED" . "IndianRed1")
             ("CANCELLED" . "grey")))
#+end_src
** Org utilities
*** Org superstar
Nos permite modificar los encabezados y los modos
#+name: org superstar
#+begin_src emacs-lisp :tangle no :noweb yes
  (use-package org-superstar
              :demand t  
              :ensure t
  	    :config
  	    (setq org-superstar-headline-bullets-list '("◉" "●" "○" "✿" "" "󰓎" ""))
              (setq org-superstar-item-bullet-alist '((?+ . ?➤) (?- . ?✦)))
              (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1))))
#+end_src
*** Org modern
Org modern nos permite modernizar el estilo visual del orgmode para que se vea más moderno por supuesto si queremos que alguna cosa se vea como normalmente podemos modificarlo en cualquier momento
#+name: org modern
#+begin_src emacs-lisp :tangle no :noweb yes
;; ;; Modern Org mode interface
(use-package org-modern
    :hook (org-mode . global-org-modern-mode)
    :custom
    (org-modern-keyword t)
    (org-modern-table nil)
    (org-modern-star 'replace)
    (org-modern-replace-stars "◉○◈◇✿✳")
    (org-modern-list '((?+ . "➤") (?- . "✦") (?* . "•")))
    (org-modern-todo-faces
          '(("TODO" :background "coral" :foreground "black")
            ("NEXT" :background "cyan" :foreground "black")
            ("PAUSED" :background "IndianRed1" :foreground "black")
            ("PROG" :background "orange" :foreground "black")
            ("WAITING" :background "yellow")
            ("DONE" :background "green" :foreground "white"))))
#+end_src
*** Desactivando algunas indentaciones raras en org mode
#+begin_src emacs-lisp
  (electric-indent-mode 0)
  (setq org-edit-src-content-indentation 0
        org-src-preserve-indentation nil) 
#+end_src
*** Ajustando otras cosas en relacion a indentacion
#+begin_src emacs-lisp
(setq org-src-tab-acts-natively t
      org-src-fontify-natively t)
#+end_src
*** Cargándolo todo
Diversas utilidades de org mode para que se vea todo mejor  
#+begin_src emacs-lisp :noweb yes
(use-package org-appear
       :hook
(org-mode . org-appear-mode))
  <<org modern>>
(use-package ox-epub
        :demand t)
(use-package ox-reveal)
#+end_src 
** Configuración de org-capture
#+begin_src emacs-lisp
(setq org-capture-templates
        `(("t" "Tarea" entry
           (file+headline "~/org/agenda.org" "Tareas")
           "* TODO %?\n  Creado: %U\n  %i\n  %a")
          ("n" "Nota" entry
           (file+headline "~/org/notes.org" "Notas")
           "* %? :nota:\n  Creado: %U\n  %i\n %a")
	  ("e" "Evento" entry
	   (file+headline "~/org/agenda.org" "Evento")
	   "* WAITING %?\n"
	   )
          ("j" "Diario" entry
           (file+datetree "~/org/diario.org")
           "* Titulo de Entrada: %?\n")
	   ("p" "Project" entry
           (file+headline "~/org/proyectos.org" "Proyectos")
           "* PROJ %?\n")))
#+end_src
** Configuración de Org Babel
#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (scheme . t)
     (python . t)
     (shell . t)
     ))
#+end_src
*** Org auto tangle
Hace que en según que caso el tangle sea automático
#+begin_src emacs-lisp
  (use-package org-auto-tangle
    :defer t
    :hook (org-mode . org-auto-tangle-mode))
#+end_src
** Otras cosas
#+begin_src emacs-lisp
(use-package toc-org
    :demand t
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src
** Org Crypt
Encriptar entradas de archivos ~.org~ usando una clave GPG
#+begin_src emacs-lisp
  (use-package org-crypt
      :ensure nil
      :after org
      :config
      (setq org-tags-exclude-from-inheritance (quote ("crypt")))
      :custom
      (org-crypt-key "oscarodriguez56@gmail.com"))
#+end_src
** Org contrib
Incluyo el paquete org-contrib, para tener ob-ledger y poder usar mi contabilidad personal con ledger
#+begin_src emacs-lisp
 (use-package org-contrib
  :after org
  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((ledger . t))))
#+end_src
* Paquetes
** Nerd Icons
Hace que emacs tenga iconos chulos y que además funcione en terminal con esos iconos
#+begin_src emacs-lisp
  (use-package nerd-icons
    ;; :custom
    ;; The Nerd Font you want to use in GUI
    ;; "Symbols Nerd Font Mono" is the default and is recommended
    ;; but you can use any other Nerd Font if you want
    ;; (nerd-icons-font-family "Symbols Nerd Font Mono")
    )
  (use-package nerd-icons-dired
    :hook
    (dired-mode . nerd-icons-dired-mode))
  (use-package nerd-icons-completion
    :config
    (nerd-icons-completion-mode)
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))
(use-package nerd-icons-corfu
   :after corfu
   :config
   (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src
** Calfw
Hace que el calendario pueda verse bonito
#+begin_src emacs-lisp
(use-package calfw
  :config
  (setq cfw:org-overwrite-default-keybinding t)) ;; atajos de teclado de la agenda org-mode
  (setq cfw:display-calendar-holidays t) ;; para esconder fiestas calendario emacs

(use-package calfw-org
  :ensure t
  :config
  (setq cfw:org-overwrite-default-keybinding t)
  :bind ([f8] . cfw:open-org-calendar))
#+end_src
** Vterm
Un emulador de terminal muy potente dentro de emacs, que me gusta un poco
#+begin_src emacs-lisp
(use-package vterm
  :defer t
:bind
(:map
 vterm-mode-map
 ("C-y" . vterm-yank)
 ("C-q" . vterm-send-next-key)))
(use-package vterm-toggle)
(global-set-key (kbd "C-c g") 'vterm-toggle)
#+end_src
** Eat
Actualmente la uso por la integracion que proporciona con Eshell.
#+begin_src emacs-lisp
   ;; ;; Aun no soportado en la shell de comandos que uso
  (use-package eat
     :ensure t)
#+end_src
** Dired sidebar
#+begin_src emacs-lisp
(use-package dired-sidebar
    :ensure t
    :defer t
    :commands (dired-sidebar-toggle-sidebar)
    :init
    (setq dired-sidebar-theme 'nerd)
    (setq dired-sidebar-use-term-integration t)
    (setq dired-sidebar-use-custom-font t))

  (use-package dired-git
    :ensure t)
(global-set-key (kbd "C-c s") 'dired-sidebar-toggle-sidebar)
#+end_src
** Autorevert
Hace que un buffer modificado desde otro lugar se refresque solo
#+begin_src emacs-lisp
(use-package autorevert
:ensure nil
:diminish
:hook (after-init . global-auto-revert-mode))
#+end_src
** Eshell
Shell que permite usar comandos elisp, se puede mejorar la experiencia usando eat gracias al eat-eshell-mode
#+begin_src emacs-lisp
  (setq eshell-prompt-function
        (lambda ()
          (let ((status (if (= eshell-last-command-status 0)
                            (propertize "✔" 'face '(:foreground "green"))
                          (propertize "✘" 'face '(:foreground "red")))))
            (concat
  	   (propertize " " 'face '(:foreground "cyan"))
             (propertize (user-login-name))
             "@"
             (propertize (system-name) 'face '(:foreground "green"))
             " "
             (propertize (abbreviate-file-name (eshell/pwd)) 'face '(:foreground "yellow"))
             " " status "\n"
             " "))))

  (defun eshell/clear ()
    "Borrar completamente el historial de eshell usando `clear-scrollback`."
    (interactive)
    (eshell-clear-scrollback))

        (use-package eshell
          :ensure nil
  	 :hook ((eshell-load . eat-eshell-mode)
  		(eshell-load . eat-eshell-visual-command-mode))
  	:config
  	(setq eshell-scroll-to-bottom-on-input t   ;; Desplazar abajo al escribir
  	      eshell-buffer-maximum-lines 5000     ;; Limitar líneas en el buffer
                eshell-hist-ignoredups t             ;; Evitar duplicados en el historial
  		      eshell-destroy-buffer-when-process-dies t) ;; Cerrar buffer si el proceso muere
  	)
        (use-package eshell-toggle
        :ensure t
        :custom
      (eshell-toggle-size-fraction 3))
        (use-package eshell-syntax-highlighting
          :after esh-mode
          :config
          (eshell-syntax-highlighting-global-mode +1))
        (global-set-key (kbd "C-c t") 'eshell-toggle)
#+end_src
** Flyspell
Habilita la correccion ortografica al vuelo.
#+begin_src emacs-lisp
(use-package flyspell
      :ensure nil
      :defer t
      :init
      :config
      (setq ispell-silently-savep t
        flyspell-case-fold-duplications t
        flyspell-issue-message-flag nil
        flyspell-default-dictionary "es_ES"
        ispell-program-name "hunspell"
        ispell-alternate-dictionary "/usr/share/dict/words") ;; Instalar paquete words en a
     :hook (text-mode . flyspell-mode)
     :bind(("M-<f7>" . flyspell-buffer)
           ("<f7>" . flyspell-word)))

(global-set-key (kbd "M-<f7>") 'dictionary-switcher)
  (use-package flyspell-correct
    :after (flyspell)
    :bind (("C-;" . flyspell-auto-correct-previous-word)
           ("<f7>" . flyspell-correct-wrapper)))
#+end_src
** Undo-tree
Hace que el sistema de desacer cambios use una estructura de arbol que se puede navegar
#+begin_src emacs-lisp
(use-package undo-tree
:init
(global-undo-tree-mode 1)
:custom
(undo-tree-visualizer-timestamps t)
(undo-tree-visualizer-diff t)
(undo-tree-auto-save-history nil))

#+end_src
** Treemacs
#+begin_src emacs-lisp
(use-package treemacs)
(global-set-key (kbd "C-c f") 'treemacs)
#+end_src
** Ledger
#+begin_src emacs-lisp
(use-package ledger-mode
  :ensure t)
#+end_src
** Embark
#+begin_src emacs-lisp
(use-package embark
    :bind
    (("C-." . embark-act)
     ("C-:" . embark-dwim)
     ("C-h B" . embark-bindings)))

(use-package embark-consult
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))
#+end_src
** Paquetes parar o hacer más amena funcionalidad normal de Emacs
*** Dashboard
El dashboard que me aparece al principio cuando abre el programa
#+begin_src emacs-lisp :noweb yes
  ;; use-package with package.el:
  (use-package dashboard
   :ensure t 
   :init
   (setq initial-buffer-choice 'dashboard-open)
   (setq dashboard-set-heading-icons t)
   (setq dashboard-display-icons-p t)
   (setq dashboard-set-file-icons t)
   (setq dashboard-set-heading-icons t)
   (setq dashboard-set-file-icons t)
   (setq dashboard-center-content t)
   (setq dashboard-vertically-center-content t)
   (setq dashboard-banner-logo-title "Emacs Kawaii")
   (setq dashboard-banner-logo-title (format "Bienvenido a Emacs %s, %s" emacs-version user-full-name))
   ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
   (setq dashboard-startup-banner "~/.config/emacs/images/kawaii-sm.png")  ;; use custom image as banner
   (setq dashboard-center-content nil) ;; set to 't' for centered content
   (setq dashboard-items '((recents . 5)
                           (agenda . 5 )
                           (bookmarks . 3)))
   (setq dashboard-item-names '(("Recent Files:" . "Archivos Recientes:")
  				("Bookmarks:" . "Marcadores:")
  				("Agenda for the coming week:" . "Agenda para la proxima semana:")
  				))


   :config
    (dashboard-modify-heading-icons '((recents   . "nf-oct-file")
                                    (projects  . "nf-oct-rocket")
                                    (bookmarks . "nf-oct-bookmark")
                                    (agenda    . "nf-oct-calendar")
                                    (registers . "nf-oct-note")))
   (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
    (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
   (dashboard-setup-startup-hook))
  (global-set-key (kbd "<f10>") 'open-dashboard)
    <<abrir dashboard>>
#+end_src
*** Doom modeline
Para retocar la barra de abajo
#+begin_src emacs-lisp
  (use-package doom-modeline
      :hook (elpaca-after-init-hook . doom-modeline-mode)
      :config
      (setq doom-modeline-height 24)
      (setq doom-modeline-icon t)
      (setq doom-modeline-major-mode-icon t)
      (setq doom-modeline-major-mode-color-icon t))
#+end_src
*** Vertico
Completacion minimalista y más vistosa
#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode)
  :custom
  (vertico-count 15)                    ; Número de candidatos a mostrar
  (vertico-resize t)
  (vertico-cycle t)
  (vertico-sort-function 'vertico-sort-history-alpha))
;; Use vertico posframe cuando use EXWM, o cuando use un tiling window manager a pantalla completa
;;(use-package vertico-posframe)
#+end_src
*** Marginalia
#+begin_src emacs-lisp
(use-package marginalia
      :init
      (marginalia-mode))
#+end_src
*** Orderless
#+begin_src emacs-lisp
(use-package orderless
  :defer t
:custom
(completion-styles '(orderless basic))
(completion-category-defaults nil)
(completion-category-overrides
 '((file (styles partial-completion)))))
#+end_src
*** Consult
Sustituye cosas como la tipica busqueda el cambio de buffer o así con una alternativa más
potente
#+begin_src emacs-lisp
  (use-package consult
    :demand t
  :bind (
         ("C-c M-x" . consult-mode-command)
         ;; ("C-c k" . consult-kmacro)
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ("M-g o" . consult-outline)               ;; Alternativa: consult-org-heading
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ("M-s d" . consult-find)                  ;; Alternativa: consult-fd
         ("M-s g" . consult-grep)
         ("C-s" . consult-line)))
  (global-set-key (kbd "C-c o") 'consult-org-agenda)
#+end_src
*** Which key
Muestra de una mejor forma las opciones de teclas a pulsar a continuacion
#+begin_src emacs-lisp
   (use-package which-key
    :ensure nil
    :delight
    :config
    (which-key-mode)
    (setq which-key-idle-delay 0.3)
    (setq which-key-dont-use-unicode nil)
    (setq which-key-separator " → " )
    (setq which-key-ellipsis "…"))
#+end_src
** Organizer
Un plugin propio que me da alguna funcionalidad que valoro bastante a nivel personal
#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "Organizer/" user-emacs-directory))
  (use-package organizer
    :ensure nil
    :config
    (global-set-key (kbd "<f12>")  'organizer-index)
    (add-to-list 'organizer-files `("Libros" . ,(expand-file-name "Libros.org" org-directory)))
    (add-to-list 'organizer-files `("Finanzas" . ,(expand-file-name "Finanzas.org" org-directory))))
#+end_src
** Olivetti
En el caso de olivetti tambien le añado encima la función que me activa una especie de modo sin distracciones
#+begin_src emacs-lisp :noweb yes
  <<sin distracciones>>
  (use-package olivetti
    :demand t
    :bind
    (("<f9>" . ews-distraction-free)))
#+end_src

** Eradio
Radio en Emacs
#+begin_src emacs-lisp
(use-package eradio
  :defer t
  :init
  (setq eradio-player '("mpv" "--no-video" "--no-terminal" "--force-seekable"))
  :config
  (setq eradio-channels '(("MGT Radio" . "https://stream.zeno.fm/koq3futfevouv") ;Esto con el punto se usa para crear un par asi podemos extraer uno u otro
                        ("Radio asiatica" . "https://stream.zeno.fm/vwvzwtapjrpvv")
			("Radio Libretics" . "https://stream-170.zeno.fm/a79lrhms108uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhNzlscmhtczEwOHV2IiwiaG9zdCI6InN0cmVhbS0xNzAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IndQLS1ld3VYVGV5RjcxNUtmaXdMRkEiLCJpYXQiOjE3NDIxNTQ3NzIsImV4cCI6MTc0MjE1NDgzMn0.nR6YeM5BOcjVXbKfFaSLO6v_kLFFvdgnbGRtaO_UblY")
			)))
(global-set-key (kbd "C-x r e") 'eradio-toggle)
(global-set-key (kbd "C-x r p") 'eradio-play)
#+end_src
** Doc View, Nov
Esto no lo uso al menos ahora por eso he desactivado el tangle
#+begin_src emacs-lisp :tangle no
(use-package doc-view
  :demand t
 :ensure nil
 :custom
(doc-view-resolution 300)
(doc-view-mupdf-use-svg t)
(large-file-warning-threshold (* 50 (expt 2 20))))

(use-package nov
  :demand t
:init
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode)))
#+end_src
** Typst
Alternativa moderna a LaTeX, tiene una sintaxis más parecida a Markdown
#+begin_src emacs-lisp
(use-package typst-mode
  :ensure (:type git :host github :repo "Ziqi-Yang/typst-mode.el"))
#+end_src
** Elfeed
Programa para lectura de fuentes rss
#+begin_src emacs-lisp
    (use-package elfeed
        :bind
        ("C-x w" . elfeed))
  #+end_src
*** Elfeed protocol
#+begin_src emacs-lisp
    (use-package elfeed-protocol
        :ensure t
        :demand t
        :after elfeed
        :config
        (elfeed-protocol-enable)
        :custom
        (elfeed-use-curl t)
        (elfeed-set-timeout 36000)
        (elfeed-log-level 'debug)
        (elfeed-protocol-feeds (list
                       (list "fever+https://Mester@rss.hostux.net"
                             :api-url "https://Mester@rss.hostux.net/api/fever.php"
                             :password (string-trim (shell-command-to-string "pass show freshrss"))))))
#+end_src
*** Elfeed goodies
No lo estoy usando no me atrajo tanto
#+begin_src emacs-lisp :tangle no
    (use-package elfeed-goodies
      :ensure t
      :config (elfeed-goodies/setup))
#+end_src
*** Elfeed dashboard
#+begin_src emacs-lisp
(use-package elfeed-dashboard
  :ensure t
  :config
  (setq elfeed-dashboard-file (expand-file-name "elfeed-dashboard" user-emacs-directory))
  ;; update feed counts on elfeed-quit
  (advice-add 'elfeed-search-quit-window :after #'elfeed-dashboard-update-links))
#+end_src
** Markdown
Permitir el uso de Markdown en Emacs con cierto resaltado
#+begin_src emacs-lisp
(use-package markdown-mode
  :demand t
:commands (markdown-mode gfm-mode)
:mode (("README\\.md\\'" . gfm-mode)
       ("\\.md\\'" . gfm-mode)
       ("\\.markdown\\'" . markdown-mode))
:init (setq markdown-command "markdown2")
:config
(setq visual-line-column 80)
(setq markdown-fontify-code-blocks-natively t)
(setq markdown-enable-math t))
#+end_src
** Supersave
Herramienta para el auto guardado, me permite guardar de forma automatica si el cursor
deja Emacs si cambio de buffer en emacs y tambien esta configurado para guardar en inactividad 
#+begin_src emacs-lisp
(use-package super-save
  :config
  (setq super-save-triggers
  '(other-window  ; Al cambiar de ventana
    switch-to-buffer  ; Al cambiar de buffer
    mouse-leave-buffer-hook)) ; Al mover el ratón fuera de Emacs
  (super-save-mode 1)
  (setq super-save-idle-duration 0.3)  ; 0.3 segundos de inactividad
  (setq super-save-auto-save-when-idle t)) ; Opcional: guardar también en inactividad
#+end_src
** Adaptative wrap
#+begin_src emacs-lisp
(use-package adaptive-wrap
  :config
  (adaptive-wrap-prefix-mode))
#+end_src
** Fish mode
Para abrir scripts para la shell fish
#+begin_src emacs-lisp
(use-package fish-mode
  :ensure t
  :demand t)
#+end_src
** I3wm mode
Para abrir la config de i3 o sway, ahora que he tenido que volver a usar i3 algunas veces para asuntos cuando Wayland no me sirve sera util
#+begin_src emacs-lisp
(use-package i3wm-config-mode
  :demand t
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("/sway/.*config.*/" . i3wm-config-mode))
(add-to-list 'auto-mode-alist '("/sway/config\\'" . i3wm-config-mode)))
#+end_src
** Cosas más
#+begin_src emacs-lisp
  (use-package savehist
    :ensure nil
    :init
    (savehist-mode))
  
  (use-package jsonrpc
    :ensure t)
#+end_src
** Programación
#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src
*** Flycheck
#+begin_src emacs-lisp
(use-package flycheck-pycheckers)

(use-package flycheck-pos-tip
  :ensure t
  :defer t
  :hook
  (flycheck-mode . flycheck-pos-tip-mode))
#+end_src
*** Magit
No es 100% imprescindible ni solo debe usarse para eso pero en la practica
#+begin_src emacs-lisp
  (use-package transient)
  (use-package magit
     :bind
     ("C-x g" . magit-status))

   (use-package git-gutter
     :defer 0.3
     :delight
     :init (global-git-gutter-mode))

   (use-package git-timemachine
     :defer 1
     :delight)
#+end_src
*** Eldoc box
Para que la documentación de funciones y demás mostradas por eldoc aparezca en caja
#+begin_src emacs-lisp
  (use-package eldoc-box
    :ensure t
    :defer t
    :after eldoc
    :init (setq eldoc-box-hover-mode t))
#+end_src
*** Corfu + Cape
Soporte para el auto completado de una manera más 🐱
#+begin_src emacs-lisp
;; Corfu: interfaz mínima y rápida de completado en buffer
(use-package corfu
  :ensure t
  :custom
  (corfu-separator ?\s)  ; separador de palabra
  (corfu-cycle t)                 ; Allows cycling through candidates
  (corfu-auto t)                  ; Enable auto completion
  (corfu-auto-prefix 2)
  (corfu-auto-delay 0.1)
  (corfu-popupinfo-delay '(0.5 . 0.2))
  (corfu-preview-current 'insert) ; insert previewed candidate
  (corfu-preselect 'prompt)
  (corfu-on-exact-match nil)
  :init
  (global-corfu-mode)
  (corfu-history-mode)
  (corfu-popupinfo-mode))         ; activación global

;; Cape: extensiones para completion-at-point
(use-package cape
  :ensure t
  :init
  (add-hook 'completion-at-point-functions #'cape-dabbrev)
  (add-hook 'completion-at-point-functions #'cape-file)
  (add-hook 'completion-at-point-functions #'cape-elisp-block)
  (add-hook 'completion-at-point-functions #'cape-emoji))
;; Atajos prácticos
(global-set-key (kbd "M-<tab>") #'completion-at-point) ; TAB para completado
#+end_src

**** Configuraciones extra para corfu
#+begin_src emacs-lisp
(use-package emacs
  :ensure nil
  :custom
  ;; TAB cycle if there are only few candidates
  ;; (completion-cycle-threshold 3)

  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (tab-always-indent 'complete)

  ;; Emacs 30 and newer: Disable Ispell completion function.
  ;; Try `cape-dict' as an alternative.
  (text-mode-ispell-word-completion nil)

  ;; Hide commands in M-x which do not apply to the current mode.  Corfu
  ;; commands are hidden, since they are not used via M-x. This setting is
  ;; useful beyond Corfu.
  (read-extended-command-predicate #'command-completion-default-include-p))

#+end_src
**** Kind icon
#+begin_src emacs-lisp :tangle no
(use-package kind-icon
  :after corfu
  :custom (kind-icon-default-face 'corfu-default)
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+end_src
*** Yasnippet
Habilita el uso de snippets
#+begin_src emacs-lisp
  (use-package yasnippet
    :defer t)
  (add-hook 'org-mode-hook 'yas-minor-mode)
  (add-hook 'prog-mode-hook 'yas-minor-mode)
  (add-hook 'lsp-mode 'yas-minor-mode)
  (use-package yasnippet-snippets)
(use-package yasnippet-capf
  :after cape
  :config
  (add-to-list 'completion-at-point-functions #'yasnippet-capf)
  (setq yasnippet-capf-lookup-by 'name))
#+end_src

*** LSP
Configuracion de LSP
#+begin_src emacs-lisp
  (use-package lsp-mode
    :init
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-c l")
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
           (rust-mode . lsp)
  	 (mhtml-mode . lsp)
	   (html-mode . lsp)
           (clojure-mode . lsp)
           ;; if you want which-key integration
           (lsp-mode . lsp-enable-which-key-integration)
  	       (python-mode . lsp)
  	       (js-mode . lsp))
    :commands lsp)
;; optionally
(use-package lsp-ui :commands lsp-ui-mode
:config
(setq lsp-ui-doc-enable t
      lsp-ui-doc-position 'at-point
      lsp-ui-doc-delay 0.5
      lsp-ui-peek-enable t
      lsp-ui-doc-show-with-cursor t))
#+end_src
*** Lenguajes
Aquí estarán los paquetes para los modos mayores y otras cosas para lenguajes de programación específicos
**** Python
Ajustes varios para python
#+begin_src emacs-lisp
   (use-package lsp-pyright
  :ensure t
  :custom (lsp-pyright-langserver-command "pyright") ;; or basedpyright
  :hook (python-mode . (lambda ()
                          (require 'lsp-pyright)
                          (lsp))))  ; or lsp-deferred
#+end_src
**** Scheme
Lenguaje de programacion bastante particular al que todavia no le he pillado todo
el potencial
#+begin_src emacs-lisp
  (use-package geiser
  :ensure t)

(use-package geiser-guile  ;; Si usas Guile Scheme
  :ensure t)
  (use-package flymake-guile
    :defer t)
#+end_src
**** Clojure
#+begin_src emacs-lisp
(use-package cider)
#+end_src
**** Rust
Lenguaje de programacion conocido por su velocidad y caracteristicas de seguridad en memoria
#+begin_src emacs-lisp
(use-package rust-mode) ;; Rust

(use-package cargo-mode
    :defer t
    :hook
    (rust-mode . cargo-minor-mode)    :config
    (setq compilation-scroll-output t))

#+end_src
**** Lua
#+begin_src emacs-lisp
(use-package lua-mode)
#+end_src
**** Java
Lenguaje de programacion que estoy aprendiendo en los estudios usarlo desde aqui es un poco complicado
#+begin_src emacs-lisp
  (use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
  
  (use-package flymake-gradle
    :defer t)

  (use-package java-snippets
    :defer t)
#+end_src
*** Projectile
Gestion de proyectos cosa que puede ser util para el aspecto organizativo
#+begin_src emacs-lisp
(use-package projectile
  :init (projectile-mode +1)
  :bind-keymap ("C-c p" . projectile-command-map))
#+end_src
*** Tressiter
#+begin_src emacs-lisp
(use-package treesit-auto
  :config
  (global-treesit-auto-mode))
#+end_src
*** Rainbow mode y Rainbow delimiters
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
         (clojure-mode . rainbow-delimiters-mode)
         (prog-mode . rainbow-delimiters-mode)))

(use-package rainbow-mode
:defer t
:hook org-mode prog-mode)
#+end_src
*** Flymake
#+begin_src emacs-lisp
  (use-package flymake
    :ensure t
    :defer t
    :hook
    (prog-mode . flymake-mode))

  (use-package flymake-flycheck
    :ensure t
    :defer t
    :hook
    (flymake-mode-hook . flymake-flycheck-auto))
  (with-eval-after-load 'flymake-mode
    (define-key flymake-mode-map (kbd "M-n") #'flymake-goto-next-error))
#+end_src

* Finalización del fichero
Esto es para aplicar algunas buenas formas al programar
#+begin_src emacs-lisp
  (provide 'init)
  ;;; init.el ends here
#+end_src
