#+title: Configuraciones
#+author: Mester
#+email: oscarodriguez56@gmail.com
#+description: Configuración de Emacs
#+property: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+auto_tangle: t

* Comienzo de la configuración
** Otras configs basicas
*** Ajustes del recolector de basura 
Aqui definimos ajustes al recolector de basura el plan es que esto se añada a las cosas del early-init.el para de esa manera,
configurar esos detalles antes de que cargue lo demás, son más que nada optimizaciones
#+name: Recolector de basura
#+begin_src emacs-lisp :tangle no
;; Garbage collector optimization
(setq gcmh-idle-delay 5)
(setopt gcmh-high-cons-threshold (* 1024 1024 1024))
(setq comp-deferred-compilation t)
(setq comp-async-jobs-number 8)
#+end_src
*** Ajustes del early-init.el
Aqui añadimos algunas configuraciones basicas para el uso de elpaca como desabilitar el gestor de paquetes por defecto, es lo que va normalmente en el archivo [[file:early-init.el][early-init.el]]
#+begin_src emacs-lisp :tangle ./early-init.el :mkdirp yes :noweb yes
(setq package-enable-at-startup nil) ;; Desactivamos el gestor de paquetes de Emacs para poder usar elpaca
(setq byte-compile-warnings '(not obsolete))
(setq warning-suppress-log-types '((comp) (bytecomp)))
(setq native-comp-async-report-warnings-errors 'silent)
(setenv "LSP_USE_PLISTS" "true")
(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 4 1024 1024))
<<Recolector de basura>>
(provide 'early-init)
#+end_src
** Añadiendo lexical binding
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src
* Configuraciones básicas
** Añadir ruta al directorio de carga
Esto es para hacer que algunos scripts de uso propio sean utilizables
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src
** Elpaca
El gestor de paquetes que utilizo, junto con lo necesario para instalarlo si no esta.
#+begin_src emacs-lisp
(defvar elpaca-installer-version 0.11)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:
;;(use-package general :demand t)
;;(elpaca-wait)

;;Turns off elpaca-use-package-mode current declartion
;;Note this will cause the declaration to be interpreted immediately (not deferred).
;;Useful for configuring built-in emacs features.
;;(use-package emacs :elpaca nil :config (setq ring-bell-function #'ignore))

;; Don't install anything. Defer execution of BODY
;;(elpaca nil (message "deferred"))
#+end_src
** Apariencia
*** Tema visual
**** Algun ajuste que otro
El ajuste custom-safe-themes es para que los temas personalizados carguen sin problema incluso si se me olvida el =:no-confirm=
#+begin_src emacs-lisp :tangle ./init.el
(setq custom-safe-themes t)
#+end_src
**** Tema Catppuccin
El tema visual a utilizar estando disponible aqui la configuracion
#+begin_src emacs-lisp
(use-package catppuccin-theme
  :config 
  (load-theme 'catppuccin t))
#+end_src
**** Tema ef
#+begin_src emacs-lisp :tangle no
  (use-package ef-themes
    :ensure t
    :config
    (setq ef-themes-variable-pitch-ui t
          ef-themes-mixed-fonts t))
#+end_src
*** Doom themes
#+begin_src emacs-lisp :tangle no
    (use-package doom-themes
      :ensure t
      :config
      (load-theme 'doom-moonlight :no-confirm))
#+end_src

*** Ajustes de fuentes y alguna cosa
**** Diversos ajustes de apariencia
Esto incluye todo ajustes relacionados a la apariencia así que creo que deberia estar aquí
#+begin_src emacs-lisp
    (tool-bar-mode -1)                                            ; Desactivar la barra de herramientas
    (menu-bar-mode -1)                                            ; Desactivar la barra de menús
    (scroll-bar-mode -1)                                          ; Desactivar la barra de desplazamiento visible
    (tooltip-mode -1)
    (set-fringe-mode 10)        ; Give some breathing room
   (add-to-list 'default-frame-alist '(fullscreen . maximized))
(setq void-text-area-pointer 'text)
(set-mouse-color (cdr (assoc 'mouse-color (frame-parameters))))
(setq-default cursor-type 'bar)
(delete-selection-mode t)

(setq use-dialog-box nil)
(display-time-mode 1)
#+end_src
**** Ajustes diversos
Aqui estan los ajustes de tipografia, que utilizo
#+begin_src emacs-lisp
(set-face-attribute 'default nil
  :font "Aporetic Sans Mono"
  :height 110
  :weight 'medium)
(set-face-attribute 'variable-pitch nil
  :font "Aporetic Sans"
  :height 110
  :weight 'medium)
(set-face-attribute 'fixed-pitch nil
  :font "Aporetic Sans Mono"
  :height 1.0
  :weight 'medium)
;; Makes commented text and keywords italics.
;; This is working in emacsclient but not emacs.
;; Your font must have an italic face available.
(set-face-attribute 'font-lock-comment-face nil
  :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil
  :slant 'italic)

;; This sets the default font on all graphical frames created after restarting Emacs.
;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
;; are not right unless I also add this method of setting the default font.
;;(add-to-list 'default-frame-alist '(font . "JetBrains Mono NerdFont-10"))

;; Uncomment the following line if line spacing needs adjusting.
(setq-default line-spacing 0.3)

(add-hook 'text-mode-hook #'variable-pitch-mode)
#+END_SRC
[[#CUSTOM_ORG_BLOCKS][Configuracion para bloques especificos del modo org]]
**** Ajustes en otros aspectos
Pendiente de implementar es para asegurarse que el modo HTML tenga monoespacido para mayor
comodidad tambien puede llegar a servir para otras cosas
#+begin_src emacs-lisp
(defun my/mhtml-use-fixed-pitch ()
  "Usar fuente monoespaciada en mhtml-mode."
  (setq buffer-face-mode-face 'fixed-pitch)
  (buffer-face-mode 1))
(add-hook 'mhtml-mode-hook #'my/mhtml-use-fixed-pitch)
#+end_src
*** Opacidad
Esta es la opacidad que el editor aplica por defecto
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 92)) ; For all new frames henceforth
#+end_src
*** Electric pair
#+begin_src emacs-lisp
(electric-pair-mode t)
#+end_src
** Configuración de IRC
Configuración del cliente erc
#+BEGIN_SRC emacs-lisp
(setq erc-nick "mester")
(setq erc-prompt-for-password (string-trim (shell-command-to-string "cat ~/Descargas/Conjuntos\ contraseña/password_irc")))
(setq erc-track-enable-keybindings t)
(setq erc-fill-column 120
      erc-fill-function 'erc-fill-static
      erc-fill-static-center 20)
#+END_SRC
** Configuraciones personales varias
Añadiendo ajustes como mi nombre completo, desactivando barra de herramientas y otras cosas
#+BEGIN_SRC emacs-lisp
(setopt user-full-name "Oscar")
  (setopt inhibit-startup-message t
        use-short-answers t
	blink-matching-parent t)
  #+end_src
*** Configuracion zoom
La configuracion de los atajos de zoom
#+begin_src emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
#+end_src
*** Ubicacion custom file
#+begin_src emacs-lisp
(setq custom-file (locate-user-emacs-file "custom-vars.el"))
(load custom-file 'noerror 'nomessage)
#+end_src
*** Configuraciones diversas
Aquí se tratan configuraciones especificas útiles para diversos aspectos
**** Formato hora
Configura el formato de la hora
#+name: formato hora
#+begin_src emacs-lisp :tangle no
  display-time-24hr-format t             ; Muestra el reloj en formato 24 hrs
  display-time-format "%H:%M"             ; Le da formato a la hora
#+end_src
**** Archivos de bloqueo
Impide la creación de ficheros de bloqueo que a veces son muy coñazo al menos para mi
#+name: lock config
#+begin_src emacs-lisp :tangle no
create-lockfiles nil                    ; Impido la creación de ficheros .#
#+end_src
**** Deshabilitar sistema de auto guardado propio
Este sistema de auto guardado es muy coñazo por los archivos que genera así que lo quito, y lo cambio por [[*Supersave][SuperSave]]
#+name: native auto save
#+begin_src emacs-lisp :tangle no
auto-save-default nil                   ; Deshabilita #file#
#+end_src
**** Archivos de copia de seguridad
Configura la creación de archivos de backup para mantener las cosas más simples y practicas
#+name: backup
#+begin_src emacs-lisp :tangle no
make-backup-files nil                   ; No realiza backups de ficheros
#+end_src
**** Estableciendo configuraciones
#+begin_src emacs-lisp :noweb yes
  (setq
   <<formato hora>>
   <<native auto save>>
   load-prefer-newer t                     ; Prefiere la versión más reciente de un archivo.
   select-enable-clipboard t               ; Sistema de fusión y portapapeles de Emacs.
   vc-follow-symlinks t                    ; Siempre sigue los enlaces simbólicos.
   <<backup>>
  ;; org-footnote-section "Referencias:"  ; cambio footnotes por referencias
   ;; global-hl-line-mode t                ; Highlight current line
   kill-ring-max 128                       ; Longitud máxima del anillo de matar
   <<lock config>>
   )
 #+end_src
*** Uso de la tecla escape pues para el escape
O algo asi
#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src
** Configuración del calendario
Ajustes del calendario dias de la semana, meses los festivos y otros ajustes del calendario. 📆
#+begin_src emacs-lisp
(setopt calendar-month-name-array
      ["Enero" "Febrero" "Marzo" "Abril" "Mayo" "Junio"
       "Julio" "Agosto" "Septiembre" "Octubre" "Noviembre" "Diciembre"])

(setopt calendar-day-name-array
      ["Domingo" "Lunes" "Martes" "Miércoles" "Jueves" "Viernes" "Sábado"])

(setq org-icalendar-timezone "Europe/Madrid") ;; timezone
(setopt calendar-week-start-day 1) ;; la semana empieza el lunes
;;(setq european-calendar-style t) ;; estilo europeo
(setq calendar-date-style 'iso)
(setopt calendar-holidays '((holiday-fixed 1 1 "Año nuevo")
			  (holiday-fixed 5 17 "Dia de las letras gallegas")
			  (holiday-fixed 10 12 "Día de la Hispanidad")
			  (holiday-fixed 11 01 "Todos los Santos")
			  (holiday-fixed 12 06 "Constitución")
			  (holiday-fixed 3 28 "Reconquista de Vigo")
			  (holiday-fixed 5 1 "Dia del Trabajo")
			  (holiday-fixed 12 24 "Nochebuena")
			  (holiday-fixed 12 25 "Navidad")))
#+end_src
* Funciones propias
** Recargar la configuración
Esta función sirve para recargar la configuracion activa sin cerrar Emacs, no funciona
en todos los casos hay veces que hay que cerrar el programa
#+begin_src emacs-lisp
(defun os/reload-config ()
  "Recargar configuracion Emacs"
  (interactive)
  (load-file (expand-file-name "init.el" user-emacs-directory))
  (ignore (elpaca-process-queues)))
(global-set-key (kbd "C-c r") 'os/reload-config)
#+end_src
** Abrir configuración
Abrir el archivo de configuración usado en este caso abro el README.org que se edita para obtener el archivo de configuracion
#+begin_src emacs-lisp
(defun os/open-config ()
  "Abrir configuracion de emacs"
  (interactive)
  (find-file "~/.config/emacs/README.org"))
(global-set-key (kbd "C-x c") 'os/open-config)
#+end_src
** Dictionary Switcher
Función propia para cambiar entre mis diccionarios más usados
#+begin_src emacs-lisp
(defun dictionary-switcher()
  "Cambiar entre los diccionarios de Español, Esperanto e Ingles mediante un menu interactivo solo entre esos y solo a un diccionario distinto al seteado."
  (interactive)
  (let* ((dic ispell-current-dictionary)
         (change
	  (completing-read "Seleccione el diccionario a usar: " '("eo" "es_ES" "en_US") nil t)))
    (unless (string= dic change)
      (ispell-change-dictionary change)
      (message "Diccionario cambiado desde %s a %s" dic change))))
#+end_src
** Toggle webserver
Activa un servidor web con auto refresco
#+begin_src emacs-lisp
(defun toggle-webserver ()
"Function to toggle a not much bigger webserver ChatGPT helping me to fix some things
This function allow to activate the webserver when you use but if there is a process of webserver the function kill it"
   (interactive)
   (let ((proc (get-process "webserver")))
         (if (and proc (eq (process-status proc) 'run))  ;; Verifica si el proceso está corriendo
             (progn
                (delete-process "webserver")
                (message "Webserver stopped"))
                (make-process :name "webserver" :command '("npx" "browser-sync" "start" "--server" "--files" "**/*") :buffer "*webserver*" :filter (lambda (_proc output)
                 (when (string-match "Local: http://localhost:3000" output) ;; Verificamos a traves de la salida si el servidor ya se ha desplegado
                   (message " ✅ Webserver started")))))))
#+end_src
** Buffer temporal en modo Org
Permite crear un buffer temporal en modo org el cual puede ser usado para tomar notas temporales que no están asociadas a algún archivo útil
cuando necesitas crear notas para algo puntual simplemente organizando información pero luego no lo necesitas para nada más, también da la posibilidad de guardarlo como archivo
#+begin_src emacs-lisp
(defun org-temp-buffer ()
   "Acceder a un buffer temporal de orgmode"
   (interactive)
   (if (get-buffer "*orgtemp*")
         (switch-to-buffer "*orgtemp*")
         (switch-to-buffer (get-buffer-create "*orgtemp*"))
         (insert (format "#+title: Org Temporal Buffer\n#+description: Espacio para la toma de notas temporales\n#+author: %s\n\n" user-full-name))
         (org-mode)))
#+end_src
** Modo sin distracciones
No es mia pero es muy util ya que me permite hacerlo mucho con el tema de distracción
#+name: sin distracciones
#+begin_src emacs-lisp :tangle no
 (defun ews-distraction-free ()
  "Distraction-free writing environment using Olivetti package."
  (interactive)
  (if (equal olivetti-mode nil)
      (progn
        (window-configuration-to-register 1)
        (delete-other-windows)
        (text-scale-set 2)
        (olivetti-mode t))
    (progn
      (if (eq (length (window-list)) 1)
          (jump-to-register 1))
      (olivetti-mode 0)
      (text-scale-set 0))))
#+end_src
** Abrir dashboard
Me permite abrir el dashboard
#+name: abrir dashboard
#+begin_src emacs-lisp :tangle no
  (defun open-dashboard ()
    "Abre el buffer *dashboard* y salta al primer widget."
    (interactive)
    (delete-other-windows)
    ;; Refresca  dashboard buffer
    (if (get-buffer dashboard-buffer-name)
        (kill-buffer dashboard-buffer-name))
    (dashboard-insert-startupify-lists)
    (switch-to-buffer dashboard-buffer-name))
#+end_src
* Org Mode
** Encabezados
Esto me permite aplicar mis configuraciones de preferencia a los encabezados tengo una lista que contiene listas asociativas con la información necesaria, y aprovecho las
funciones car y cdr para extraer los múltiples objetos de esa lista con la información y ejecutar la macro custom-set-faces con la información requerida y que fue puesta en la lista
#+begin_src emacs-lisp
(dolist (item '((org-level-1 . (1.5 . outilne-1))
		  (org-level-2 . (1.4 . outline-2))
	          (org-level-3 . (1.25 . outline-3))
                  (org-level-3 . (1.1 . outline-3))
                  (org-document-title . (1.7 . nil))))
  (custom-set-faces `( ,(car item) ((t (:inherit ,(cdr (cdr item)) :height ,(car (cdr item))))))))
#+end_src
** Ajustes generales
Ajustes de Org Mode
*** Configurar archivos
Aqui establezco los archivos tipo org que mi configuración va a requerir
#+begin_src emacs-lisp
(setopt org-directory "~/org/")
(setopt diary-file (expand-file-name "diario.org" org-directory))
(setq org-default-notes-file (expand-file-name "notes.org" org-directory))
(setq org-agenda-files (list (expand-file-name "agenda.org" org-directory) (expand-file-name "proyectos.org" org-directory)))
(setq org-archive-location "~/org/%s_archivo.org::datetree/")
#+end_src
*** Añadiendo ajustes varios
#+begin_src emacs-lisp
(setopt org-export-with-drawers nil
      org-export-with-todo-keywords nil
      org-export-with-broken-links t
      org-export-with-toc nil
      org-export-with-smart-quotes t
      org-export-date-timestamp-format "%d %B %Y"
      org-list-allow-alphabetical t)

 (setq org-return-follows-link  t) ;; Hace que pulsando Enter funcione el seguir el enlace
 (require 'org-tempo)               
(use-package org
    :ensure nil)
(setq org-ellipsis "▼")
(setq-default org-startup-indented t
                    org-pretty-entities t
                    org-use-sub-superscripts "{}"
                    org-hide-emphasis-markers t
                    org-startup-with-inline-images t
                    image-actual-width '(300))
(add-hook 'org-mode-hook 'org-indent-mode)
        (global-set-key (kbd "C-c c") 'org-capture)
        (global-set-key (kbd "C-c a") 'org-agenda)
#+end_src
*** Ajustes del todo
Ajustes en relacion al sistema de gestión de tareas en cuanto a tareas pendientes
#+begin_src emacs-lisp
(setopt org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "WAITING(w)" "PAUSED(P)" "|" "DONE(d)" "CANCELLED(c)")))
    (setopt org-todo-keyword-faces
           '(("TODO" . "coral")
             ("NEXT" . "cyan")
 	        ("WAITING" . "yellow")
             ("DONE" . "green")
             ("PAUSED" . "IndianRed1")
             ("CANCELLED" . "grey")))
#+end_src
** Org utilities
*** Org superstar
Nos permite modificar los encabezados y los modos, actualmente no lo estoy usando en su lugar uso Org Modern
#+name: org superstar
#+begin_src emacs-lisp :tangle no :noweb yes
  (use-package org-superstar
              :demand t  
              :ensure t
  	    :config
  	    (setq org-superstar-headline-bullets-list '("◉" "●" "○" "✿" "" "󰓎" ""))
              (setq org-superstar-item-bullet-alist '((?+ . ?➤) (?- . ?✦)))
              (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1))))
#+end_src
*** Org modern
Org modern nos permite modernizar el estilo visual del orgmode para que se vea más moderno por supuesto si queremos que alguna cosa se vea como normalmente podemos modificarlo en cualquier momento
#+name: org modern
#+begin_src emacs-lisp :tangle no :noweb yes
;; ;; Modern Org mode interface
(use-package org-modern
    :hook   (org-mode . org-modern-mode)
            (org-agenda-finalize . org-modern-agenda)
    :custom
    (org-modern-block-indent t)  ; to enable org-modern-indent when org-indent is active
    (org-modern-keyword t)
    (org-modern-table nil)
    (org-modern-star 'replace)
    (org-modern-replace-stars "◉○◈◇✿✳")
    (org-modern-checkbox
     '((?X . "✔")
       (?- . "┅")
       (?\s . "")))
    (org-modern-list '((?+ . "➤") (?- . "✦") (?* . "•")))
    (org-modern-todo-faces
          '(("TODO" :background "coral" :foreground "black")
            ("NEXT" :background "cyan" :foreground "black")
            ("PAUSED" :background "IndianRed1" :foreground "black")
            ("WAITING" :background "yellow")
            ("DONE" :background "green" :foreground "white")
            ("CANCELLED" :background "gray" :foreground "white")))
    (org-modern-label-border 1))
#+end_src
*** Desactivando algunas indentaciones raras en org mode
#+begin_src emacs-lisp
  (electric-indent-mode 0)
  (setq org-edit-src-content-indentation 0
        org-src-preserve-indentation nil) 
#+end_src
*** Ajustando otras cosas en relacion a indentacion
#+begin_src emacs-lisp
(setq org-src-tab-acts-natively t
      org-src-fontify-natively t)
#+end_src
*** Cargándolo todo
Diversas utilidades de org mode para que se vea todo mejor  
#+begin_src emacs-lisp :noweb yes
(use-package org-appear
       :hook
(org-mode . org-appear-mode))
  <<org modern>>
(use-package ox-epub
        :demand t)
(use-package ox-reveal)
#+end_src 
** Configuración de org-capture
#+begin_src emacs-lisp
(setq org-capture-templates
        `(("t" "Tarea" entry
           (file+headline "~/org/agenda.org" "Tareas")
           "* TODO %?\n  Creado: %U\n  %i\n  %a")
          ("n" "Nota" entry
           (file+headline "~/org/notes.org" "Notas")
           "* %? :nota:\n  Creado: %U\n  %i\n %a")
	  ("e" "Evento" entry
	   (file+headline "~/org/agenda.org" "Evento")
	   "* WAITING %?\n"
	   )
          ("j" "Diario" entry
           (file+datetree "~/org/diario.org")
           "* Titulo de Entrada: %?\n")
	   ("p" "Project" entry
           (file+headline "~/org/proyectos.org" "Proyectos")
           "*  %?\n")))
#+end_src
** Configuración de Org Babel
Aqui configuro los lenguajes que utilizo en org babel para hacer tangle y todo eso
#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (scheme . t)
     (python . t)
     (shell . t)
     ))
#+end_src
*** Org auto tangle
Hace que en según que caso el tangle sea automático
#+begin_src emacs-lisp
  (use-package org-auto-tangle
    :defer t
    :hook (org-mode . org-auto-tangle-mode))
#+end_src
** Otras cosas
#+begin_src emacs-lisp
(use-package toc-org
    :demand t
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src
** Org Crypt
Encriptar entradas de archivos ~.org~ usando una clave GPG
#+begin_src emacs-lisp
  (use-package org-crypt
      :ensure nil
      :after org
      :config
      (setq org-tags-exclude-from-inheritance (quote ("crypt")))
      :custom
      (org-crypt-key "oscarodriguez56@gmail.com"))
#+end_src
** Org contrib
Incluyo el paquete org-contrib, para tener ob-ledger y poder usar mi contabilidad personal con ledger
#+begin_src emacs-lisp
 (use-package org-contrib
  :after org
  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((ledger . t))))
#+end_src
* Paquetes
** EMMS
Es un reproductor de musica desde Emacs permite usar mpv para reproducir musica desde el editor
#+begin_src emacs-lisp :tangle no
(use-package emms
  :config
  (require 'emms-setup)
  (emms-all)
  (emms-default-players))
#+end_src
** Nerd Icons
Hace que emacs tenga iconos chulos y que además funcione en terminal con esos iconos
#+begin_src emacs-lisp
  (use-package nerd-icons)
  (use-package nerd-icons-dired
    :hook
    (dired-mode . nerd-icons-dired-mode))
  (use-package nerd-icons-completion
    :config
    (nerd-icons-completion-mode)
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))
(use-package nerd-icons-corfu
   :after corfu
   :config
   (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src
** Calfw
Hace que el calendario pueda verse bonito
#+begin_src emacs-lisp
(use-package calfw
  :config
  (setq cfw:org-overwrite-default-keybinding t)) ;; atajos de teclado de la agenda org-mode
  (setq cfw:display-calendar-holidays t) ;; para esconder fiestas calendario emacs

(use-package calfw-org
  :ensure t
  :config
  (setq cfw:org-overwrite-default-keybinding t)
  :bind ([f8] . cfw:open-org-calendar))
#+end_src
** Vterm
Un emulador de terminal muy potente dentro de emacs, que me gusta un poco
#+begin_src emacs-lisp
(use-package vterm
  :defer t
  :bind
  (:map
   vterm-mode-map
   ("C-y" . vterm-yank)
   ("C-q" . vterm-send-next-key)))
(use-package vterm-toggle
  :bind (("C-c g" . vterm-toggle)))
#+end_src
** Eat
Actualmente la uso por la integracion que proporciona con Eshell.
#+begin_src emacs-lisp
   ;; ;; Aun no soportado en la shell de comandos que uso
  (use-package eat
     :ensure t)
#+end_src
** Dired sidebar
#+begin_src emacs-lisp
(use-package dired-sidebar
    :ensure t
    :defer t
    :commands (dired-sidebar-toggle-sidebar)
    :init
    (setopt dired-sidebar-theme 'nerd)
    (setopt dired-sidebar-use-term-integration t)
    (setopt dired-sidebar-use-custom-font t))

  (use-package dired-git
    :ensure t)
(global-set-key (kbd "C-c s") 'dired-sidebar-toggle-sidebar)
#+end_src
** Autorevert
Hace que un buffer modificado desde otro lugar se refresque solo
#+begin_src emacs-lisp
(use-package autorevert
:ensure nil
:diminish
:hook (after-init . global-auto-revert-mode))
#+end_src
** Eshell
Shell que permite usar comandos elisp, se puede mejorar la experiencia usando eat gracias al eat-eshell-mode
#+begin_src emacs-lisp
(setq eshell-prompt-function
      (lambda ()
        (let ((status (if (= eshell-last-command-status 0)
                          (propertize "✔" 'face '(:foreground "green"))
                        (propertize "✘" 'face '(:foreground "red")))))
          (concat
	   (propertize " " 'face '(:foreground "cyan"))
           (propertize (user-login-name))
           "@"
           (propertize (system-name) 'face '(:foreground "green"))
           " "
           (propertize (abbreviate-file-name (eshell/pwd)) 'face '(:foreground "yellow"))
           " " status "\n"
           " "))))

(defun eshell/clear ()
  "Borrar completamente el historial de eshell usando `clear-scrollback`."
  (interactive)
  (eshell-clear-scrollback))

      (use-package eshell
        :ensure nil
	 :hook ((eshell-load . eat-eshell-mode)
		(eshell-load . eat-eshell-visual-command-mode))
	:config
	(setopt eshell-scroll-to-bottom-on-input t   ;; Desplazar abajo al escribir
	      eshell-buffer-maximum-lines 5000     ;; Limitar líneas en el buffer
          eshell-hist-ignoredups t             ;; Evitar duplicados en el historial
	  eshell-destroy-buffer-when-process-dies t) ;; Cerrar buffer si el proceso muere
	)
      (use-package eshell-toggle
      :ensure t
      :custom
    (eshell-toggle-size-fraction 3))
      (use-package eshell-syntax-highlighting
        :after esh-mode
        :config
        (eshell-syntax-highlighting-global-mode +1))
      (global-set-key (kbd "C-c t") 'eshell-toggle)
#+end_src
** Flyspell
Habilita la correccion ortografica al vuelo.
#+begin_src emacs-lisp
(use-package flyspell
      :ensure nil
      :defer t
      :init
      :config
      (setopt ispell-silently-savep t
        flyspell-case-fold-duplications t
        flyspell-issue-message-flag nil
        flyspell-default-dictionary "es_ES"
        ispell-program-name "hunspell"
        ispell-alternate-dictionary "/usr/share/dict/words") ;; Instalar paquete words en a
     :hook (text-mode . flyspell-mode)
     :bind(("M-<f7>" . flyspell-buffer)
           ("<f7>" . flyspell-word)))

(global-set-key (kbd "M-<f7>") 'dictionary-switcher)
  (use-package flyspell-correct
    :after (flyspell)
    :bind (("C-;" . flyspell-auto-correct-previous-word)
           ("<f7>" . flyspell-correct-wrapper)))
#+end_src
** Undo-tree
Hace que el sistema de desacer cambios use una estructura de arbol que se puede navegar
#+begin_src emacs-lisp
(use-package undo-tree
:init
(global-undo-tree-mode 1)
:custom
(undo-tree-visualizer-timestamps t)
(undo-tree-visualizer-diff t)
(undo-tree-auto-save-history nil))

#+end_src
** Treemacs
#+begin_src emacs-lisp
(use-package treemacs
 :config 
(setopt treemacs-hide-gitignored-files-mode t)
   treemacs-project-follow-cleanup t
   treemacs-width 45
   treemacs-width-is-initially-locked nil
   delete-by-moving-to-trash t
  treemacs-collapse-dirs 3
  treemacs-display-in-side-window t
  treemacs-is-never-other-window t
  treemacs-indentation 2
  treemacs-indentation-string " "
  treemacs-filewatch-mode t
  treemacs-git-mode 'deferred
  treemacs-text-scale 1
  treemacs-move-files-by-mouse-dragging nil
  treemacs-move-forward-on-expand t
  treemacs-pulse-on-success t
  treemacs-file-event-delay 0
  treemacs-deferred-git-apply-delay 0
  treemacs-git-commit-diff-mode 1)
  (add-hook 'treemacs-mode-hook #'treemacs-project-follow-mode)
(use-package treemacs-nerd-icons
  :after nerd-icons
  :config
  (treemacs-load-theme "nerd-icons"))
(global-set-key (kbd "C-c f") 'treemacs)
#+end_src
** Ledger
#+begin_src emacs-lisp
(use-package ledger-mode
  :ensure t)
#+end_src
** Embark
#+begin_src emacs-lisp
(use-package embark
    :bind
    (("C-." . embark-act)
     ("C-:" . embark-dwim)
     ("C-h b" . embark-bindings)))

(use-package embark-consult
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

** Paquetes parar o hacer más amena funcionalidad normal de Emacs
*** Dashboard
El dashboard que me aparece al principio cuando abre el programa
#+begin_src emacs-lisp :noweb yes
;; use-package with package.el:
(use-package dashboard
  :ensure t
  :custom-face
  (dashboard-footer-face ((t (:inherit font-lock-doc-face :slant italic :height 0.98))))
  :custom
  (initial-buffer-choice 'dashboard-open)
  (dashboard-set-heading-icons t)
  (dashboard-set-file-icons t)
  (dashboard-icon-type 'nerd-icons)
  (dashboard-display-icons-p t)     ; display icons on both GUI and terminal
  (dashboard-vertically-center-content t)
  (dashboard-banner-logo-title (format "Bienvenido a Emacs %s, %s" emacs-version user-full-name))
  (dashboard-startup-banner "~/.config/emacs/images/kawaii-sm.png")
  (dashboard-items '((recents . 5)
                     (agenda . 5)
                     (bookmarks . 3)))
  (dashboard-item-names '(("Recent Files:" . "Archivos Recientes:")
                          ("Bookmarks:" . "Marcadores:")
                          ("Agenda for the coming week:" . "Agenda para la próxima semana:")))
  (dashboard-navigator-buttons
   `((
      (,(nerd-icons-mdicon "nf-md-cog" :height 1.1 :v-adjust 0.0)
       "Settings" "Open Config file"
       (lambda (&rest _) (os/open-config)))
      (,(nerd-icons-flicon "nf-linux-hyprland" :height 1.1 :v-adjust 0.0)
       "WM Settings" "Hyprland settings"
       (lambda (&rest _) (find-file "~/.config/hypr/hyprland.conf")))
      (,(nerd-icons-mdicon "nf-md-notebook" :height 1.1 :v-adjust 0.0)
       "Index" "Index of my Org"
       (lambda (&rest _) (organizer-index))))))
  (dashboard-startupify-list
   '(dashboard-insert-newline
     dashboard-insert-banner
     dashboard-insert-newline
     dashboard-insert-banner-title
     dashboard-insert-newline
     dashboard-insert-navigator
     dashboard-insert-items
     dashboard-insert-newline
     dashboard-insert-footer))
  :config
  (dashboard-modify-heading-icons '((recents   . "nf-oct-file")
                                     (projects  . "nf-oct-rocket")
                                     (bookmarks . "nf-oct-bookmark")
                                     (agenda    . "nf-oct-calendar")
                                     (registers . "nf-oct-note")))
  (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (dashboard-setup-startup-hook))
(global-set-key (kbd "<f10>") 'open-dashboard)
  <<abrir dashboard>>
#+end_src

#+RESULTS:
: open-dashboard

*** Doom modeline
Para retocar la barra de abajo
#+begin_src emacs-lisp
  (use-package doom-modeline
      :hook (elpaca-after-init-hook . doom-modeline-mode)
      :custom
      (doom-modeline-height 29)
      (doom-modeline-icon t)
      (doom-modeline-major-mode-icon t)
      (doom-modeline-major-mode-color-icon t))
#+end_src
*** Os modeline
#+begin_src emacs-lisp :tangle no
(require 'os-modeline)
#+end_src
*** Vertico
Completacion minimalista y más vistosa en el minibuffer
#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode)
  :custom
  (vertico-count 15)                    ; Número de candidatos a mostrar
  (vertico-resize t)
  (vertico-cycle t)
  (vertico-sort-function 'vertico-sort-history-alpha))
;; Use vertico posframe cuando use EXWM, o cuando use un tiling window manager a pantalla completa
;;(use-package vertico-posframe)
#+end_src
*** Marginalia
Provee anotaciones en el minibuffer para mejorar la experiencia de completado
#+begin_src emacs-lisp
(use-package marginalia
   :after vertico
   :custom
  (marginalia-annotators
   '(marginalia-annotators-heavy marginalia-annotators-lv))
      :init
      (marginalia-mode))
#+end_src
*** Orderless
#+begin_src emacs-lisp
(use-package orderless
  :defer t
:custom
(completion-styles '(orderless basic))
(completion-category-defaults nil)
(completion-category-overrides
 '((file (styles partial-completion)))))
#+end_src
*** Consult
Sustituye cosas como la tipica busqueda el cambio de buffer o así con una alternativa más
potente
#+begin_src emacs-lisp
  (use-package consult
    :demand t
  :bind (
         ("C-c M-x" . consult-mode-command)
         ;; ("C-c k" . consult-kmacro)
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ("M-g o" . consult-outline)               ;; Alternativa: consult-org-heading
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ("M-s d" . consult-find)                  ;; Alternativa: consult-fd
         ("M-s g" . consult-grep)
         ("C-s" . consult-line)))
  (global-set-key (kbd "C-c o") 'consult-org-agenda)
#+end_src
*** Which key
Muestra de una mejor forma las opciones de teclas a pulsar a continuacion
#+begin_src emacs-lisp
(use-package which-key
 :ensure nil
 :delight
 :config
 (which-key-mode)
 (setopt which-key-idle-delay 0.3)
         which-key-dont-use-unicode nil
         which-key-separator " → " 
         which-key-ellipsis "…"))
#+end_src
** Organizer
Un plugin propio que me da alguna funcionalidad que valoro bastante a nivel personal
#+begin_src emacs-lisp
  (use-package organizer
    :ensure nil
    :load-path "Organizer/"
    :config
    (global-set-key (kbd "<f12>")  'organizer-index)
    (add-to-list 'organizer-files `("Libros" . ,(expand-file-name "Libros.org" org-directory)))
    (add-to-list 'organizer-files `("Finanzas" . ,(expand-file-name "Finanzas.org" org-directory))))
#+end_src
** Olivetti
En el caso de olivetti tambien le añado encima la función que me activa una especie de modo sin distracciones
#+begin_src emacs-lisp :noweb yes
  <<sin distracciones>>
  (use-package olivetti
    :demand t
    :bind
    (("<f9>" . ews-distraction-free)))
#+end_src

** Eradio
Radio en Emacs
#+begin_src emacs-lisp
(use-package eradio
  :defer t
  :init
  (setopt eradio-player '("mpv" "--no-video" "--no-terminal" "--force-seekable"))
  :config
  (setopt eradio-channels '(("MGT Radio" . "https://stream.zeno.fm/koq3futfevouv") ;Esto con el punto se usa para crear un par asi podemos extraer uno u otro
                        ("Radio asiatica" . "https://stream.zeno.fm/vwvzwtapjrpvv")
			("Radio Libretics" . "https://stream-170.zeno.fm/a79lrhms108uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJhNzlscmhtczEwOHV2IiwiaG9zdCI6InN0cmVhbS0xNzAuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IndQLS1ld3VYVGV5RjcxNUtmaXdMRkEiLCJpYXQiOjE3NDIxNTQ3NzIsImV4cCI6MTc0MjE1NDgzMn0.nR6YeM5BOcjVXbKfFaSLO6v_kLFFvdgnbGRtaO_UblY")
			("Cadena Dial" . "http://playerservices.streamtheworld.com/api/livestream-redirect/CADENADIAL.mp3"))))
(global-set-key (kbd "C-x r e") 'eradio-toggle)
(global-set-key (kbd "C-x r p") 'eradio-play)
#+end_src
** Doc View, Nov
Esto no lo uso al menos ahora por eso he desactivado el tangle
#+begin_src emacs-lisp :tangle no
(use-package doc-view
  :demand t
 :ensure nil
 :custom
(doc-view-resolution 300)
(doc-view-mupdf-use-svg t)
(large-file-warning-threshold (* 50 (expt 2 20))))

(use-package nov
  :demand t
:init
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode)))
#+end_src
** Elfeed
Programa para lectura de fuentes rss
#+begin_src emacs-lisp
(use-package elfeed
    :custom-face
    (elfeed-search-unread-title-face ((t (:inherit fixed-pitch))))
    :bind
    ("C-x w" . elfeed))
  #+end_src
*** Elfeed protocol
Esto permite leer feeds de servicios RSS externos al propio ordenador
#+begin_src emacs-lisp
    (use-package elfeed-protocol
        :ensure t
        :demand t
        :after elfeed
        :config
        (elfeed-protocol-enable)
        :custom
        (elfeed-use-curl t)
        (elfeed-set-timeout 36000)
        (elfeed-log-level 'debug)
        (elfeed-protocol-feeds (list
                       (list "fever+https://Mester@rss.hostux.net"
                             :api-url "https://Mester@rss.hostux.net/api/fever.php"
                             :password (string-trim (shell-command-to-string "pass show freshrss"))))))
#+end_src
*** Elfeed goodies
No lo estoy usando no me atrajo tanto
#+begin_src emacs-lisp :tangle no
    (use-package elfeed-goodies
      :ensure t
      :config (elfeed-goodies/setup))
#+end_src
*** Elfeed dashboard
Permite tener un dashboard para organizarlo todo usando org-mode
#+begin_src emacs-lisp
(use-package elfeed-dashboard
  :ensure t
  :config
  (setq elfeed-dashboard-file (expand-file-name "elfeed-dashboard" user-emacs-directory))
  ;; update feed counts on elfeed-quit
  (advice-add 'elfeed-search-quit-window :after #'elfeed-dashboard-update-links))
#+end_src
** Supersave
Herramienta para el auto guardado, me permite guardar de forma automatica si el cursor
deja Emacs si cambio de buffer en emacs y tambien esta configurado para guardar en inactividad 
#+begin_src emacs-lisp
(use-package super-save
  :config
  (setq super-save-triggers
  '(other-window  ; Al cambiar de ventana
    switch-to-buffer  ; Al cambiar de buffer
    mouse-leave-buffer-hook)) ; Al mover el ratón fuera de Emacs
  (super-save-mode 1)
  (setq super-save-idle-duration 0.3)  ; 0.3 segundos de inactividad
  (setq super-save-auto-save-when-idle t)) ; Opcional: guardar también en inactividad
#+end_src
** Adaptative wrap
#+begin_src emacs-lisp
(use-package adaptive-wrap
  :config
  (adaptive-wrap-prefix-mode))
#+end_src
** Modos extra archivos
Modos extra para algunos archivos específicos
*** Markdown
Permitir el uso de Markdown en Emacs con cierto resaltado
#+begin_src emacs-lisp
(use-package markdown-mode
  :demand t
:commands (markdown-mode gfm-mode)
:mode (("README\\.md\\'" . gfm-mode)
       ("\\.md\\'" . gfm-mode)
       ("\\.markdown\\'" . markdown-mode))
:init (setq markdown-command "markdown2")
:config
(setq visual-line-column 80)
(setq markdown-fontify-code-blocks-natively t)
(setq markdown-enable-math t))
(use-package markdown-preview-eww
  :ensure t
  :after markdown-mode)

(use-package markdown-preview-mode
  :ensure t)
#+end_src
*** Typst
Alternativa moderna a LaTeX, tiene una sintaxis más parecida a Markdown
#+begin_src emacs-lisp
(use-package typst-mode
  :ensure (:type git :host github :repo "Ziqi-Yang/typst-mode.el"))
#+end_src
*** Hyprland
#+begin_src emacs-lisp
(use-package hyprlang-ts-mode
  :ensure t
  :custom
  (hyprlang-ts-mode-indent-offset 4)
  :config 
  (add-to-list 'auto-mode-alist '("/hypr/.*config.*/" . hyprlang-ts-mode))
(add-to-list 'auto-mode-alist '("/hypr/config\\'" . hyprlang-ts-mode)))
#+end_src
*** Fish mode
Para abrir scripts para la shell fish
#+begin_src emacs-lisp
(use-package fish-mode
  :ensure t
  :demand t)
#+end_src
*** I3wm mode
Para abrir la config de i3 o sway, ahora que he tenido que volver a usar i3 algunas veces para asuntos cuando Wayland no me sirve sera util
#+begin_src emacs-lisp
(use-package i3wm-config-mode
  :demand t
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("/sway/.*config.*/" . i3wm-config-mode))
(add-to-list 'auto-mode-alist '("/sway/config\\'" . i3wm-config-mode)))
#+end_src
** Cosas más
#+begin_src emacs-lisp
  (use-package savehist
    :ensure nil
    :init
    (savehist-mode))
  
  (use-package jsonrpc
    :ensure t)
#+end_src
** Programación
Aquí están todos los paquetes y modos que utilizo para programar
#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
(setq display-line-numbers-type 'relative)
(setq-default display-fill-column-indicator-column 79)
(add-hook 'prog-mode-hook #'display-fill-column-indicator-mode)
#+end_src
*** Flycheck
#+begin_src emacs-lisp
(use-package flycheck-pycheckers)
(use-package flycheck
  :ensure t
  :init
  (setq flycheck-check-syntax-automatically
        '(save mode-enabled idle-change))
  (setq flycheck-idle-change-delay 0))

(setq flycheck-checker-cache "~/.flycheck-cache")
(setq flycheck-indication-mode nil)
(use-package flycheck-pos-tip
  :ensure t
  :defer t
  :hook
  (flycheck-mode . flycheck-pos-tip-mode))

(add-hook 'python-mode-hook #'flycheck-mode)
#+end_src

*** Magit
No es 100% imprescindible ni solo debe usarse para eso pero en la practica
#+begin_src emacs-lisp
  (use-package transient)
  (use-package magit
     :bind
     ("C-x g" . magit-status))

   (use-package git-gutter
     :defer 0.3
     :delight
     :init (global-git-gutter-mode))

   (use-package git-timemachine
     :defer 1
     :delight)
#+end_src
*** Eldoc box
Para que la documentación de funciones y demás mostradas por eldoc aparezca en caja
#+begin_src emacs-lisp
  (use-package eldoc-box
    :ensure t
    :defer t
    :after eldoc
    :init (setq eldoc-box-hover-mode t))
#+end_src
*** Corfu + Cape
Soporte para el auto completado de una manera más 🐱 cape proporciona los backends que se pueden aprovechar para las labores de autocompletado.
#+begin_src emacs-lisp
;; Corfu: interfaz mínima y rápida de completado en buffer
(use-package corfu
  :ensure t
  :custom
  (corfu-separator ?\s)  ; separador de palabra
  (corfu-cycle t)                 ; Allows cycling through candidates
  (corfu-auto t)                  ; Enable auto completion
  (corfu-auto-prefix 2)
  (corfu-auto-delay 0.1)
  (corfu-popupinfo-delay '(0.5 . 0.2))
  (corfu-preview-current 'insert) ; insert previewed candidate
  (corfu-on-exact-match nil)
  :init
  (global-corfu-mode)
  (corfu-history-mode)
  (corfu-popupinfo-mode))         ; activación global
(use-package corfu-terminal
   :after corfu
   :ensure (:type git :repo "https://codeberg.org/akib/emacs-corfu-terminal.git")
   :config
   (unless (display-graphic-p)
      (corfu-terminal-mode)))
;; Cape: extensiones para completion-at-point
(use-package cape
  :ensure t
  :init
  (add-hook 'completion-at-point-functions #'cape-abbrev)
  (add-hook 'completion-at-point-functions #'cape-dabbrev)
  (add-hook 'completion-at-point-functions #'cape-file)
  (add-hook 'completion-at-point-functions #'cape-elisp-block)
  (add-hook 'completion-at-point-functions #'cape-emoji)
  (add-hook 'completion-at-point-functions #'cape-dict)
  (add-hook 'completion-at-point-functions #'cape-keyword))
;; Atajos prácticos
(global-set-key (kbd "M-<tab>") #'completion-at-point) ; TAB para completado
#+end_src

**** Configuraciones extra para corfu
Aqui añado unas configuraciones extra para poder hacer más cosas con corfu
#+begin_src emacs-lisp
(use-package emacs
  :ensure nil
  :custom
  ;; TAB cycle if there are only few candidates
  ;; (completion-cycle-threshold 3)

  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (tab-always-indent 'complete)

  ;; Emacs 30 and newer: Disable Ispell completion function.
  ;; Try `cape-dict' as an alternative.
  (text-mode-ispell-word-completion nil)

  ;; Hide commands in M-x which do not apply to the current mode.  Corfu
  ;; commands are hidden, since they are not used via M-x. This setting is
  ;; useful beyond Corfu.
  (read-extended-command-predicate #'command-completion-default-include-p))

#+end_src
**** Kind icon
Actualmente estoy usando la alternativa nerd-icons-corfu porque como ya uso nerd-icons para lo demás no tengo tanto lio
#+begin_src emacs-lisp :tangle no
(use-package kind-icon
  :after corfu
  :custom (kind-icon-default-face 'corfu-default)
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+end_src
*** Yasnippet
Habilita el uso de snippets
#+begin_src emacs-lisp :tangle no
  (use-package yasnippet
    :defer t)
  (add-hook 'org-mode-hook 'yas-minor-mode)
  (add-hook 'prog-mode-hook 'yas-minor-mode)
  (add-hook 'lsp-mode 'yas-minor-mode)
  (use-package yasnippet-snippets)
(use-package yasnippet-capf
  :after cape
  :config
  (add-to-list 'completion-at-point-functions #'yasnippet-capf)
  (setq yasnippet-capf-lookup-by 'name))
#+end_src
*** Tempel
Una alternativa a Yasnippet que aprovecha los propios sistemas nativos de Emacs, es mi alternativa actual
#+begin_src emacs-lisp
(use-package tempel
  :bind (("M-+" . tempel-complete) ;; o el keybinding que prefieras
         ("M-*" . tempel-insert))
  :custom
  (tempel-path "~/.config/emacs/templates.el") ;; o donde quieras tus plantillas
  :init
    (defun tempel-setup-capf ()
    ;; Add the Tempel Capf to `completion-at-point-functions'.
    ;; `tempel-expand' only triggers on exact matches. Alternatively use
    ;; `tempel-complete' if you want to see all matches, but then you
    ;; should also configure `tempel-trigger-prefix', such that Tempel
    ;; does not trigger too often when you don't expect it. NOTE: We add
    ;; `tempel-expand' *before* the main programming mode Capf, such
    ;; that it will be tried first.
    (setq-local completion-at-point-functions
                (cons #'tempel-expand (cons #'tempel-complete
                      completion-at-point-functions))))
  (add-hook 'conf-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf)
  (add-hook 'org-mode-hook 'tempel-setup-capf)
  (add-hook 'lsp-mode-hook 'tempel-setup-capf)
  (add-hook 'lsp-mode 'tempel-setup-capf)
  (add-hook 'lsp-after-initialize-hook 'tempel-setup-capf)
  (add-hook 'lsp-on-idle-hook 'tempel-setup-capf)
  :config 
   (define-key tempel-map (kbd "TAB") #'tempel-next))

(use-package tempel-collection)
#+end_src
*** LSP
Configuracion de LSP
#+begin_src emacs-lisp
  (use-package lsp-mode
    :init
    (setq lsp-enable-snippet nil)
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-c l")
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
           (rust-mode . lsp)
	   (mhtml-mode . lsp)
	   (html-mode . lsp)
           ;; if you want which-key integration
           (lsp-mode . lsp-enable-which-key-integration)
  	      (python-mode . lsp)
  	      (js-mode . lsp))
    :commands lsp)
;; optionally
(use-package lsp-ui :commands lsp-ui-mode
:config
(setq lsp-ui-doc-enable t
      lsp-ui-doc-position 'at-point
      lsp-ui-doc-delay 0.5
      lsp-ui-peek-enable t
      lsp-ui-doc-show-with-cursor t))
#+end_src
*** Dap Mode 
#+begin_src emacs-lisp
(use-package dap-mode
  :ensure t
  :config
  (dap-auto-configure-mode))

#+end_src
*** Lenguajes
Aquí estarán los paquetes para los modos mayores y otras cosas para lenguajes de programación específicos
**** Python
Ajustes varios para python
#+begin_src emacs-lisp
 (use-package lsp-pyright
   :ensure t
   :custom (lsp-pyright-langserver-command "pyright") ;; or basedpyright
   :hook (python-mode . (lambda ()
                        (require 'lsp-pyright)
                        (lsp))))  ; or lsp-deferred
#+end_src
***** Trabajo con uv 
Aqui voy a definir algunas funciones para trabajar con el gestor de complementos uv si veo que me sale bien podría traspasarlo a otro plugin, y ver que puedo hacer, por ejemplo hacer algo con un modo menor para detectar si se usa uv y que solo me de las funciones ahi pero bueno eso es ya más adelante
#+begin_src emacs-lisp
(defun uv-project-run (archivo)
  "Ejecuta el archivo que desees de un proyecto con uv"
  (interactive "fSeleccione un archivo: ")
  (let ((dir default-directory))
    (if (and (file-exists-p (expand-file-name "pyproject.toml" dir)) (file-exists-p (expand-file-name "README.md" dir)) (file-exists-p (expand-file-name "main.py" dir)))
       (progn
	(start-process-shell-command "uv-project-run" "*uv-project-run*" (concat "uv run " archivo))
          (with-current-buffer "*uv-project-run*"
               (setq-local comint-prompt-read-only t)
               (setq-local comint-use-prompt-regexp t)
               (setq-local comint-prompt-regexp "^[^#$%>\n]*[#$%>] *")
               (setq-local comint-move-point-for-output 'this)
                (comint-mode))
          (split-window-below)
          (other-window 1)
	  (switch-to-buffer "*uv-project-run*"))
       (message "Los archivos que indicas no son validos necesito archivos python y que se use el gestor de proyectos UV"))))
#+end_src
**** Scheme
Lenguaje de programacion bastante particular al que todavia no le he pillado todo
el potencial
#+begin_src emacs-lisp
  (use-package geiser
  :ensure t)

(use-package geiser-guile  ;; Si usas Guile Scheme
  :ensure t)
  (use-package flymake-guile
    :defer t)
#+end_src
**** Rust
Lenguaje de programacion conocido por su velocidad y caracteristicas de seguridad en memoria
#+begin_src emacs-lisp
(use-package rust-mode) ;; Rust

(use-package cargo-mode
    :defer t
    :hook
    (rust-mode . cargo-minor-mode)    
    :config
    (setq compilation-scroll-output t))

#+end_src
**** Lua
#+begin_src emacs-lisp
(use-package lua-mode)
#+end_src
**** Java
Lenguaje de programacion que estoy aprendiendo en los estudios usarlo desde aqui es un poco complicado
#+begin_src emacs-lisp
  (use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
  
  (use-package flymake-gradle
    :defer t)
#+end_src
*** Projectile
Gestion de proyectos cosa que puede ser util para el aspecto organizativo
#+begin_src emacs-lisp
(use-package projectile
  :ensure t
  :config
  (projectile-mode +1))

(setq projectile-project-root-files '(".git"))
#+end_src
*** Tressiter
#+begin_src emacs-lisp
(use-package treesit-auto
  :config
  (global-treesit-auto-mode))
(add-to-list 'treesit-language-source-alist
        '(hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang"))
    
#+end_src
*** Rainbow mode y Rainbow delimiters
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
         (prog-mode . rainbow-delimiters-mode)))

(use-package rainbow-mode
:defer t
:hook ((org-mode . rainbow-mode) (prog-mode . rainbow-mode)))
#+end_src
*** Flymake
#+begin_src emacs-lisp
  (use-package flymake
    :ensure t
    :defer t
    :hook
    (prog-mode . flymake-mode))

  (use-package flymake-flycheck
    :ensure t
    :defer t
    :hook
    (flymake-mode-hook . flymake-flycheck-auto))
  (with-eval-after-load 'flymake-mode
    (define-key flymake-mode-map (kbd "M-n") #'flymake-goto-next-error))
#+end_src

* Ajustes de faces
Aquí introduciré los principales ajustes de faces para asegurar mayor compatibilidad con mis configuraciones
*** Ajustes a elementos del org-mode
:PROPERTIES:
:CUSTOM_ID: CUSTOM_ORG_BLOCKS
:END:
En el tema ef-themes no es necesario debido a que ya da la posibilidad de que eso funcione de forma correcta
#+begin_src emacs-lisp
(custom-set-faces
 ;; Código, bloques, verbatim, tablas
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-code ((t (:family fixed-pitch))))
 '(org-table ((t (:inherit fixed-pitch))))
 '(org-verbatim ((t (:inherit fixed-pitch))))
 '(org-formula ((t (:inherit fixed-pitch))))
 '(org-checkbox ((t (:inherit fixed-pitch))))
 ;; Estilo gris clásico para metadatos
 '(org-meta-line ((t (:inherit (shadow fixed-pitch) :slant italic)))))
#+end_src
* Finalización del fichero
Esto es para aplicar algunas buenas formas al programar en Emacs Lisp
#+begin_src emacs-lisp
  (provide 'init)
  ;;; init.el ends here
#+end_src
