// .pragma library
// Catálogo de emojis/símbolos para el menú unificado.
// Sustituye a `walker -m symbols` (elephant symbols.toml -> wl-copy).
// Campos: ch = carácter, name = nombre en español, kw = keywords para FuzzySearch.

.pragma library

function getEmojis() {
    return [
        { ch: "😀", name: "sonrisa", kw: "smile happy feliz cara" },
        { ch: "😁", name: "sonrisa dientes", kw: "grin smile feliz" },
        { ch: "😂", name: "risa llanto", kw: "laugh joy lol jaja" },
        { ch: "🤣", name: "reir suelo", kw: "rofl laugh lol" },
        { ch: "😊", name: "sonrojado", kw: "blush smile contento" },
        { ch: "😍", name: "enamorado", kw: "love heart ojos corazon" },
        { ch: "😘", name: "beso", kw: "kiss love beso" },
        { ch: "🥰", name: "amor", kw: "love smiling hearts" },
        { ch: "😎", name: "gafas sol", kw: "cool sunglasses guay" },
        { ch: "🤔", name: "pensando", kw: "thinking hmm pensar" },
        { ch: "🤨", name: "esceptico", kw: "skeptical suspicious" },
        { ch: "😐", name: "neutral", kw: "neutral meh" },
        { ch: "🙄", name: "ojos arriba", kw: "eyeroll annoyed" },
        { ch: "😴", name: "dormido", kw: "sleep dormir zzz" },
        { ch: "🤯", name: "cabeza explota", kw: "mindblown shock wow" },
        { ch: "🥳", name: "fiesta", kw: "party celebrate cumple" },
        { ch: "😭", name: "llorando", kw: "cry sad llorar sob" },
        { ch: "😤", name: "resoplido", kw: "triumph angry enfado" },
        { ch: "😡", name: "enfadado", kw: "angry rage red" },
        { ch: "🤬", name: "insulto", kw: "swear angry" },
        { ch: "🥶", name: "frio", kw: "cold ice frozen" },
        { ch: "🥵", name: "calor", kw: "hot heat sweat" },
        { ch: "🤢", name: "nausea", kw: "sick vomit verde" },
        { ch: "🤮", name: "vomito", kw: "vomit sick" },
        { ch: "🤧", name: "estornudo", kw: "sneeze sick" },
        { ch: "😷", name: "mascarilla", kw: "mask covid sick" },
        { ch: "👍", name: "pulgar arriba", kw: "like yes ok +1" },
        { ch: "👎", name: "pulgar abajo", kw: "dislike no -1" },
        { ch: "👏", name: "aplauso", kw: "clap bravo aplauso" },
        { ch: "🙏", name: "rezar gracias", kw: "pray thanks please" },
        { ch: "💪", name: "musculo", kw: "strong muscle fuerza" },
        { ch: "✌️", name: "victoria", kw: "victory peace v" },
        { ch: "🤝", name: "apreton manos", kw: "handshake deal" },
        { ch: "👋", name: "hola adios", kw: "wave hello hi" },
        { ch: "✋", name: "mano", kw: "hand stop alto" },
        { ch: "👀", name: "ojos", kw: "eyes look mirar" },
        { ch: "🧠", name: "cerebro", kw: "brain smart mente" },
        { ch: "❤️", name: "corazon rojo", kw: "heart love rojo" },
        { ch: "💔", name: "corazon roto", kw: "broken heart sad" },
        { ch: "🔥", name: "fuego", kw: "fire hot lit fuego" },
        { ch: "⭐", name: "estrella", kw: "star favorito" },
        { ch: "✨", name: "brillos", kw: "sparkles shine nuevo" },
        { ch: "💡", name: "bombilla idea", kw: "idea light bulb" },
        { ch: "🎉", name: "fiesta confeti", kw: "party tada celebracion" },
        { ch: "🎂", name: "tarta cumple", kw: "birthday cake cumple" },
        { ch: "🏆", name: "trofeo", kw: "trophy win campeon" },
        { ch: "🥇", name: "medalla oro", kw: "gold medal primero" },
        { ch: "⚽", name: "futbol", kw: "soccer football deporte" },
        { ch: "🎮", name: "mando juego", kw: "game gaming jugar" },
        { ch: "🎧", name: "auriculares", kw: "headphones music musica" },
        { ch: "🎵", name: "nota musical", kw: "music nota cancion" },
        { ch: "📷", name: "camara", kw: "camera foto" },
        { ch: "📸", name: "camara flash", kw: "camera photo foto" },
        { ch: "🖥️", name: "ordenador", kw: "computer pc desktop" },
        { ch: "💻", name: "portatil", kw: "laptop notebook" },
        { ch: "⌨️", name: "teclado", kw: "keyboard teclas" },
        { ch: "🖱️", name: "raton", kw: "mouse raton" },
        { ch: "🐧", name: "pinguino linux", kw: "penguin linux tux" },
        { ch: "🚀", name: "cohete", kw: "rocket launch deploy" },
        { ch: "🐛", name: "bicho bug", kw: "bug error fallo" },
        { ch: "🔧", name: "llave", kw: "wrench fix herramienta" },
        { ch: "⚙️", name: "engranaje", kw: "gear settings config" },
        { ch: "💾", name: "disquete guardar", kw: "save floppy guardar" },
        { ch: "📋", name: "portapapeles", kw: "clipboard copiar" },
        { ch: "📌", name: "chincheta", kw: "pin fijo" },
        { ch: "📎", name: "clip", kw: "clip attach adjunto" },
        { ch: "✂️", name: "tijeras", kw: "scissors cortar" },
        { ch: "🗑️", name: "papelera", kw: "trash delete borrar" },
        { ch: "🔒", name: "candado", kw: "lock privado" },
        { ch: "🔑", name: "llave clave", kw: "key password clave" },
        { ch: "✅", name: "check", kw: "check done ok hecho" },
        { ch: "❌", name: "cruz", kw: "cross no error" },
        { ch: "⚠️", name: "aviso", kw: "warning cuidado" },
        { ch: "❓", name: "pregunta", kw: "question ayuda" },
        { ch: "❗", name: "exclamacion", kw: "exclamation importante" },
        { ch: "➡️", name: "flecha derecha", kw: "arrow right" },
        { ch: "⬅️", name: "flecha izquierda", kw: "arrow left" },
        { ch: "⬆️", name: "flecha arriba", kw: "arrow up" },
        { ch: "⬇️", name: "flecha abajo", kw: "arrow down" },
        { ch: "🔁", name: "repetir", kw: "repeat loop" },
        { ch: "⏯️", name: "play pausa", kw: "play pause" },
        { ch: "☕", name: "cafe", kw: "coffee cafe" },
        { ch: "🍕", name: "pizza", kw: "pizza comida" },
        { ch: "🌙", name: "luna noche", kw: "moon night dark" },
        { ch: "☀️", name: "sol", kw: "sun day dia" },
        { ch: "🌧️", name: "lluvia", kw: "rain lluvia" },
        { ch: "❄️", name: "nieve", kw: "snow frio" },
        { ch: "🌈", name: "arcoiris", kw: "rainbow" },
        { ch: "🌍", name: "tierra", kw: "earth world mundo" },
        { ch: "📦", name: "caja paquete", kw: "box package" },
        { ch: "🚗", name: "coche", kw: "car coche" },
        { ch: "✈️", name: "avion", kw: "plane travel viaje" },
        { ch: "🏠", name: "casa", kw: "home casa" },
        { ch: "💼", name: "maletin trabajo", kw: "work briefcase" },
        { ch: "📚", name: "libros", kw: "books estudiar" },
        { ch: "🎓", name: "graduacion", kw: "graduation uni" },
        { ch: "💰", name: "dinero", kw: "money dinero" },
        { ch: "🛒", name: "carrito compra", kw: "cart shop compra" },
        // Símbolos técnicos (walker symbols incluye unicode además de emoji)
        { ch: "→", name: "flecha unicode", kw: "arrow unicode right" },
        { ch: "←", name: "flecha izq unicode", kw: "arrow unicode left" },
        { ch: "↑", name: "flecha arriba unicode", kw: "arrow unicode up" },
        { ch: "↓", name: "flecha abajo unicode", kw: "arrow unicode down" },
        { ch: "×", name: "por multiplicar", kw: "times multiply cross" },
        { ch: "÷", name: "dividir", kw: "divide" },
        { ch: "≠", name: "distinto", kw: "notequal distinto" },
        { ch: "≈", name: "aproximado", kw: "approx aprox" },
        { ch: "∞", name: "infinito", kw: "infinity" },
        { ch: "π", name: "pi", kw: "pi math" },
        { ch: "λ", name: "lambda", kw: "lambda" },
        { ch: "✓", name: "tick", kw: "tick check" },
        { ch: "©", name: "copyright", kw: "copyright" },
        { ch: "®", name: "registrado", kw: "registered" },
        { ch: "€", name: "euro", kw: "euro money" },
        { ch: "‼", name: "doble exclamacion", kw: "double bang" }
    ];
}
