;;; typst-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from typst-ts-compile.el

(autoload 'typst-ts-compile-and-preview "typst-ts-compile" "\
Compile & Preview.
Assuming the compile output file name is in default style." t)
(autoload 'typst-ts-compilation-mode "typst-ts-compile" "\
Customized major mode for typst watch compilation.

(fn)")
(register-definition-prefixes "typst-ts-compile" '("typst-ts-"))


;;; Generated autoloads from typst-ts-core.el

(register-definition-prefixes "typst-ts-core" '("typst-ts-"))


;;; Generated autoloads from typst-ts-edit-indirect.el

(register-definition-prefixes "typst-ts-edit-indirect" '("typst-ts-edit-indirect"))


;;; Generated autoloads from typst-ts-editing.el

(register-definition-prefixes "typst-ts-editing" '("typst-ts-"))


;;; Generated autoloads from typst-ts-embedding-lang-settings.el

(register-definition-prefixes "typst-ts-embedding-lang-settings" '("typst-ts-els-"))


;;; Generated autoloads from typst-ts-faces.el

(register-definition-prefixes "typst-ts-faces" '("typst-ts-markup-header-s"))


;;; Generated autoloads from typst-ts-lsp.el

(autoload 'typst-ts-lsp-download-binary "typst-ts-lsp" "\
Download latest tinymist binary to `typst-ts-lsp-download-path'.
Will override old versions." t)
(register-definition-prefixes "typst-ts-lsp" '("typst-ts-lsp-download-path"))


;;; Generated autoloads from typst-ts-misc-commands.el

(register-definition-prefixes "typst-ts-misc-commands" '("typst-ts-mc-"))


;;; Generated autoloads from typst-ts-mode.el

(autoload 'typst-ts-mode-preview "typst-ts-mode" "\
Open the result compile file.
FILE: file path for the result compile file.

(fn FILE)" t)
(defvar-keymap typst-ts-mode-map "C-c C-c" #'typst-ts-compile "C-c C-w" #'typst-ts-watch-mode "C-c C-p" #'typst-ts-mode-preview "M-<left>" #'typst-ts-mode-meta-left "M-<right>" #'typst-ts-mode-meta-right "M-<down>" #'typst-ts-mode-meta-down "M-<up>" #'typst-ts-mode-meta-up "M-<return>" #'typst-ts-mode-meta-return "TAB" #'typst-ts-mode-cycle "RET" #'typst-ts-mode-return "C-c '" #'typst-ts-edit-indirect)
(autoload 'typst-ts-mode "typst-ts-mode" "\
Major mode for editing Typst, powered by tree-sitter.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.typ\\'" . typst-ts-mode))
(register-definition-prefixes "typst-ts-mode" '("typst-ts-mode-"))


;;; Generated autoloads from typst-ts-watch-mode.el

(autoload 'typst-ts-watch-display-buffer "typst-ts-watch-mode" "\
Display typst watch process buffer." t)
(autoload 'typst-ts-watch-start "typst-ts-watch-mode" "\
Watch(hot compile) current typst file." t)
(autoload 'typst-ts-watch-stop "typst-ts-watch-mode" "\
Stop watch process." t)
(register-definition-prefixes "typst-ts-watch-mode" '("typst-ts-"))

;;; End of scraped data

(provide 'typst-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; typst-ts-mode-autoloads.el ends here
