;;; flymake-gradle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from flymake-gradle.el

(autoload 'flymake-gradle-setup "flymake-gradle" "\
Set up Flymake for Gradle." t)
(autoload 'flymake-gradle-add-hook "flymake-gradle" "\
Add `flymake-gradle-lint' to `flymake-diagnostic-functions'.")
(register-definition-prefixes "flymake-gradle" '("flymake-gradle-"))

;;; End of scraped data

(provide 'flymake-gradle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-gradle-autoloads.el ends here
