cursor            #ffb1c5
cursor_text_color #551d2f

foreground            #efdfe1
background            #140c0e
selection_foreground  #422930
selection_background  #e3bdc5
url_color             #e3bdc5

#: black 000000 767676
color0  #191113
color8  #3c3234
#: red cc0403 f2201f
color1  #1464ac
color9  #6cb0ed
#: green 19cb00 23fd00
color2  #e3bdc5
color10 #ffd9e1
#: yellow cecb00 fffd00
color3  #eebd92
color11 #ffdcbf
#: blue 0d73cc 1a8fff
color4  #703346
color12 #ffb1c5
#: magenta cb1ed1 fd28ff
color5  #5b3f46
color13 #e3bdc5
#: cyan 0dcdcd 14ffff
color6  #61401e
color14 #eebd92
#: white dddddd ffffff
color7  #d6c2c5
color15 #efdfe1

mark1_foreground #3a071b
mark1_background #ffd9e1
mark2_foreground #2b151b
mark2_background #ffd9e1
mark3_foreground #2d1600
mark3_background #ffdcbf

active_tab_foreground #551d2f
active_tab_background #ffb1c5
inactive_tab_foreground #ffd9e1
inactive_tab_background #703346

active_border_color #ffb1c5
inactive_border_color #551d2f
# bell_border_color #ff5a00
