# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include colors.conf
# END_KITTY_THEME
font_family      JetBrainsMono NF Propo
bold_font        JetBrainsMono NFM Bold Propo
italic_font      JetBrainsMono NFM Italic Propo
bold_italic_font JetBrainsMono NFM Bold Italic Propo
window_padding_width 2
cursor_trail 1

tab_bar_edge                bottom
font_size 11.5
cursor_shape beam
disable_ligatures never
background_opacity 0.9
tab_bar_style powerline
shell fish
