# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include colors.conf
# END_KITTY_THEME

font_family      MapleMono NF CN
#font_family	  GeistMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

enable_audio_bell no
window_padding_width 11

scrollback_indicator_opacity 0
scroll_bar_handle_opacity 0
scroll_bar_track_opacity 0
scroll_bar_track_hover_opacity 0
confirm_os_window_close 0
cursor_trail 1
background_blur 1

symbol_map U+E000-U+F8FF Symbols Nerd Font

disable_ligatures cursor

hide_window_decorations yes

tab_bar_edge                bottom
font_size 10.3
cursor_shape beam
disable_ligatures never
background_opacity 0.97
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge                bottom
tab_title_template  {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
shell fish

[blur]
background=true
